// 7 Wonders — static game data (card types, resources, cards, Wonder boards). Loaded before
// script.js. This is the file admin/index.html edits and re-exports — keep all content data
// here, keep logic in script.js. See docs/requirements.md §3/§3b for the data shapes.
//
// Types (Card, WonderBoard, GameDataShape, etc.) come from src/types.d.ts, visible here as global
// ambient declarations with no import — see that file's header for why.
"use strict";
const GameData = {
    CARD_TYPES: {
        basic: { label: "Raw Material", color: "#D4A453", colorDim: "#6B4423" },
        manufactured: { label: "Manufactured Good", color: "#808080", colorDim: "#454a52" },
        civilian: { label: "Civilian Structure", color: "#0051FF", colorDim: "#22384a" },
        scientific: { label: "Scientific Structure", color: "#00DD77", colorDim: "#22402c" },
        commercial: { label: "Commercial Structure", color: "#FBBF24", colorDim: "#4a3d1e" },
        military: { label: "Military Structure", color: "#FF2222", colorDim: "#4a2226" },
        guild: { label: "Guild", color: "#A855F7", colorDim: "#3a2a49" },
    },
    // `icon` is the illustrated artwork (game/images/icons/); `emoji` stays as a fallback for
    // contexts that can't render an <img> (e.g. admin.html's raw JSON view) and as short
    // alt/title text — see script.js's resIcon()/sciIcon() helpers.
    RESOURCES: {
        wood: { label: "Wood", emoji: "🪵", icon: "images/icons/res-wood.png" },
        clay: { label: "Clay", emoji: "🧱", icon: "images/icons/res-clay.png" },
        ore: { label: "Ore", emoji: "⛏️", icon: "images/icons/res-ore.png" },
        stone: { label: "Stone", emoji: "🪨", icon: "images/icons/res-stone.png" },
        glass: { label: "Glass", emoji: "🔷", icon: "images/icons/res-glass.png" },
        loom: { label: "Loom", emoji: "🧵", icon: "images/icons/res-loom.png" },
        papyrus: { label: "Papyrus", emoji: "📜", icon: "images/icons/res-papyrus.png" },
    },
    SCIENCE_SYMBOLS: {
        tablet: { label: "Tablet", emoji: "📚", icon: "images/icons/sym-tablet.png" },
        compass: { label: "Compass", emoji: "🧭", icon: "images/icons/sym-compass.png" },
        gear: { label: "Gear", emoji: "⚙️", icon: "images/icons/sym-gear.png" },
    },
    // Non-resource illustrated icons, same provenance/rationale as RESOURCES/SCIENCE_SYMBOLS above.
    ICONS: {
        vp: "images/icons/sym-vp.png", // laurel wreath — victory points
        coins: "images/icons/sym-coins.png", // gold coin
        shields: "images/icons/sym-shields.png", // crossed swords on a shield — military strength
        chain: "images/icons/sym-chain.png", // carved arrow — free-build chain unlock
        conflict: "images/icons/sym-conflict.png", // helmet + shield + arrows — military conflict resolution
        wonder: "images/icons/sym-wonder.png", // pyramid — generic "Wonder" glyph
    },
    // Individual card and scene images, organized by age. Each card/scene has its own file.
    // Card images are stored in:
    //   - images/cards/age1/ (All Age I cards - production, civic, trade, military, science)
    //   - images/cards/age2/ (All Age II cards)
    //   - images/cards/age3/ (All Age III cards)
    //   - images/wonders/ (Wonder board images)
    // Scene images are in:
    //   - images/scenes/ (screen background artwork)
    CARD_IMAGES: {
        // Age I cards (28 total)
        "lumber-yard": "images/cards/age1/lumber-yard.png",
        "forest-cave": "images/cards/age1/forest-cave.png",
        "ore-vein": "images/cards/age1/ore-vein.png",
        "mine": "images/cards/age1/mine.png",
        "clay-pool": "images/cards/age1/clay-pool.png",
        "clay-pit": "images/cards/age1/clay-pit.png",
        "stone-pit": "images/cards/age1/stone-pit.png",
        "quarry": "images/cards/age1/quarry.png",
        "glassworks": "images/cards/age1/glassworks.png",
        "press": "images/cards/age1/press.png",
        "loom-house": "images/cards/age1/loom-house.png",
        "scriptorium": "images/cards/age1/scriptorium.png",
        "workshop": "images/cards/age1/workshop.png",
        "apothecary": "images/cards/age1/apothecary.png",
        "baths": "images/cards/age1/baths.png",
        "altar": "images/cards/age1/altar.png",
        "theater": "images/cards/age1/theater.png",
        "well": "images/cards/age1/well.png",
        "shrine": "images/cards/age1/shrine.png",
        "statue-garden": "images/cards/age1/statue-garden.png",
        "plaza": "images/cards/age1/plaza.png",
        "tavern": "images/cards/age1/tavern.png",
        "market": "images/cards/age1/market.png",
        "trading-post": "images/cards/age1/trading-post.png",
        "caravanserai": "images/cards/age1/caravanserai.png",
        "stockade": "images/cards/age1/stockade.png",
        "garrison": "images/cards/age1/garrison.png",
        "barracks": "images/cards/age1/barracks.png",
        // Age II cards (28 total)
        "sawmill": "images/cards/age2/sawmill.png",
        "foundry": "images/cards/age2/foundry.png",
        "brickyard": "images/cards/age2/brickyard.png",
        "shelf-quarry": "images/cards/age2/shelf-quarry.png",
        "caravan": "images/cards/age2/caravan.png",
        "stained-glass-works": "images/cards/age2/stained-glass-works.png",
        "papyrus-mill": "images/cards/age2/papyrus-mill.png",
        "loom-shed": "images/cards/age2/loom-shed.png",
        "bazaar": "images/cards/age2/bazaar.png",
        "customs-house": "images/cards/age2/customs-house.png",
        "forum-market": "images/cards/age2/forum-market.png",
        "guild-exchange": "images/cards/age2/guild-exchange.png",
        "dockyard": "images/cards/age2/dockyard.png",
        "bank": "images/cards/age2/bank.png",
        "aqueduct": "images/cards/age2/aqueduct.png",
        "temple": "images/cards/age2/temple.png",
        "statue": "images/cards/age2/statue.png",
        "courtyard": "images/cards/age2/courtyard.png",
        "gardens": "images/cards/age2/gardens.png",
        "senate": "images/cards/age2/senate.png",
        "forum-hall": "images/cards/age2/forum-hall.png",
        "amphitheater": "images/cards/age2/amphitheater.png",
        "courthouse": "images/cards/age2/courthouse.png",
        "observatory": "images/cards/age2/observatory.png",
        "pharmacy": "images/cards/age2/pharmacy.png",
        "walls": "images/cards/age2/walls.png",
        "archery-range": "images/cards/age2/archery-range.png",
        "training-ground": "images/cards/age2/training-ground.png",
        // Age III cards (32 total: 15 regular + 10 guilds + 7 special)
        "pantheon": "images/cards/age3/pantheon.png",
        "gardens-palace": "images/cards/age3/gardens-palace.png",
        "town-hall": "images/cards/age3/town-hall.png",
        "palace": "images/cards/age3/palace.png",
        "obelisk": "images/cards/age3/obelisk.png",
        "senate-hall": "images/cards/age3/senate-hall.png",
        "grand-arena": "images/cards/age3/grand-arena.png",
        "university": "images/cards/age3/university.png",
        "library": "images/cards/age3/library.png",
        "monument": "images/cards/age3/monument.png",
        "sanctuary": "images/cards/age3/sanctuary.png",
        "grand-temple": "images/cards/age3/grand-temple.png",
        "fortress": "images/cards/age3/fortress.png",
        "siege-camp": "images/cards/age3/siege-camp.png",
        "citadel": "images/cards/age3/citadel.png",
        "arsenal": "images/cards/age3/arsenal.png",
        "haven": "images/cards/age3/haven.png",
        "lighthouse": "images/cards/age3/lighthouse.png",
        "chamber-of-commerce": "images/cards/age3/chamber-of-commerce.png",
        "university-of-science": "images/cards/age3/university-of-science.png",
        "observatory-tower": "images/cards/age3/observatory-tower.png",
        "lodge": "images/cards/age3/lodge.png",
        // Filler cards (not in base game, generated for spritesheet completeness)
        "marble-quarry": "images/cards/age3/marble-quarry.png",
        "glass-blowers": "images/cards/age3/glass-blowers.png",
        "metal-foundry": "images/cards/age3/metal-foundry.png",
        "silk-workshops": "images/cards/age3/silk-workshops.png",
        "military-academy": "images/cards/age3/military-academy.png",
        "merchant-house": "images/cards/age3/merchant-house.png",
        "temple-gardens": "images/cards/age3/temple-gardens.png",
        "engineers-workshop": "images/cards/age3/engineers-workshop.png",
        "harbor-tower": "images/cards/age3/harbor-tower.png",
        // Age III Guild cards (10 total)
        "spies-guild": "images/cards/age3/spies-guild.png",
        "magistrates-guild": "images/cards/age3/magistrates-guild.png",
        "workers-guild": "images/cards/age3/workers-guild.png",
        "craftsmens-guild": "images/cards/age3/craftsmens-guild.png",
        "traders-guild": "images/cards/age3/traders-guild.png",
        "philosophers-guild": "images/cards/age3/philosophers-guild.png",
        "builders-guild": "images/cards/age3/builders-guild.png",
        "shipowners-guild": "images/cards/age3/shipowners-guild.png",
        "strategists-guild": "images/cards/age3/strategists-guild.png",
        "scientists-guild": "images/cards/age3/scientists-guild.png",
        // Extra content for 5-7 player games (src/game-data.ts §"Age I/II/III extra content") —
        // reuses an existing thematically-similar image rather than commissioning new art.
        "lumber-camp": "images/cards/age1/lumber-yard.png",
        "copper-mine": "images/cards/age1/ore-vein.png",
        "clay-flats": "images/cards/age1/clay-pool.png",
        "loom-croft": "images/cards/age1/loom-house.png",
        "meeting-hall": "images/cards/age1/theater.png",
        "scholars-nook": "images/cards/age1/scriptorium.png",
        "watch-post": "images/cards/age1/stockade.png",
        "granite-pit": "images/cards/age1/stone-pit.png",
        "birch-grove": "images/cards/age1/forest-cave.png",
        "tin-vein": "images/cards/age1/mine.png",
        "glass-shed": "images/cards/age1/glassworks.png",
        "public-bath": "images/cards/age1/altar.png",
        "survey-post": "images/cards/age1/workshop.png",
        "palisade": "images/cards/age1/garrison.png",
        "clay-terrace": "images/cards/age1/clay-pit.png",
        "pine-camp": "images/cards/age1/lumber-yard.png",
        "quartz-mine": "images/cards/age1/ore-vein.png",
        "papyrus-hut": "images/cards/age1/press.png",
        "garden-shrine": "images/cards/age1/shrine.png",
        "archive-room": "images/cards/age1/apothecary.png",
        "sentry-tower": "images/cards/age1/barracks.png",
        "log-mill": "images/cards/age2/sawmill.png",
        "smeltery": "images/cards/age2/foundry.png",
        "clay-works": "images/cards/age2/brickyard.png",
        "dye-mill": "images/cards/age2/loom-shed.png",
        "plaza-hall": "images/cards/age2/courtyard.png",
        "study-hall": "images/cards/age2/courthouse.png",
        "garrison-wall": "images/cards/age2/walls.png",
        "quarry-camp": "images/cards/age2/shelf-quarry.png",
        "grove-mill": "images/cards/age2/sawmill.png",
        "ore-works": "images/cards/age2/foundry.png",
        "glass-foundry": "images/cards/age2/stained-glass-works.png",
        "civic-hall": "images/cards/age2/statue.png",
        "watch-tower": "images/cards/age2/observatory.png",
        "rampart": "images/cards/age2/archery-range.png",
        "silt-pit": "images/cards/age2/brickyard.png",
        "pine-mill": "images/cards/age2/sawmill.png",
        "stone-works": "images/cards/age2/shelf-quarry.png",
        "papyrus-hall": "images/cards/age2/papyrus-mill.png",
        "forum-annex": "images/cards/age2/forum-hall.png",
        "workshop-hall": "images/cards/age2/pharmacy.png",
        "training-yard": "images/cards/age2/training-ground.png",
        "grand-plaza": "images/cards/age3/gardens-palace.png",
        "market-row": "images/cards/age3/chamber-of-commerce.png",
        "bastion": "images/cards/age3/fortress.png",
        "regal-court": "images/cards/age3/palace.png",
        "counting-house": "images/cards/age3/haven.png",
        "grand-academy": "images/cards/age3/university-of-science.png",
        "monumental-arch": "images/cards/age3/monument.png",
        "hall-of-scholars": "images/cards/age3/library.png",
        "chart-house": "images/cards/age3/lodge.png",
    },
    WONDER_IMAGES: {
        "gizah": "images/wonders/gizah.png",
        "rhodos": "images/wonders/rhodos.png",
        "ephesos": "images/wonders/ephesos.png",
        "babylon": "images/wonders/babylon.png",
        "olympia": "images/wonders/olympia.png",
        "halikarnassos": "images/wonders/halikarnassos.png",
        "alexandria": "images/wonders/alexandria.png",
    },
    // Scene images for screens and panels
    SCENES: {
        // Age I scenes
        wonderBuild: "images/scenes/wonderBuild.png",
        discardPile: "images/scenes/discardPile.png",
        finalTriumph: "images/scenes/finalTriumph.png",
        battlefield: "images/scenes/battlefield.png",
        // Age II scenes
        defeat: "images/scenes/defeat.png",
        guildHall: "images/scenes/guildHall.png",
        wonderComplete: "images/scenes/wonderComplete.png",
        ageDawn: "images/scenes/ageDawn.png",
        // Age III scenes
        finalVictory: "images/scenes/final-victory.png",
        // Setup screen
        title: "images/scenes/title.png",
    },
    // Illustration art for card faces (game/images/). Only 3 images exist for 88 cards, so there's
    // no realistic per-type dedication (that would make e.g. every civilian card — nearly a third
    // of the deck — show the exact same photo). Instead script.js's cardArtUrl() hashes each
    // **All 88 cards now have individual images** (CARD_IMAGES above).
    // The fallback pool below is retained as a safety fallback but should never be used.
    CARD_ART: {
        pool: [],
    },
    // Base game only — the Leaders expansion and the 2-player "Free City" variant (see
    // docs/rules.md) are not implemented. Each card carries a `playerCount`: the smallest table it
    // appears at, so `playerCount <= numPlayers` selects the deck. Player counts 3-4 use the base
    // ~90-card pool; 5-7 layer in the "extra content" blocks below (`playerCount` 5/6/7) so every
    // Age still deals exactly 7 cards per player at every offered count — an Age needs 7×players
    // cards, and the physical game covers that at higher counts by adding extra copies, mostly of
    // basic resource cards. This implementation follows the same idea but with original placeholder
    // cards rather than duplicate copies of the base ones (see the per-block comments); like the
    // base pool, they're a representative sample, not the authoritative physical scaling. Guild
    // count is never the bottleneck: 10 exist and at most `numPlayers + 2` (9, at 7 players) are
    // ever needed. `buildDeckPools` throws rather than dealing a short pool, so a miscounted tier
    // fails loudly instead of silently shipping short hands.
    SUPPORTED_PLAYER_COUNTS: [3, 4, 5, 6, 7],
    // Human-readable text for each `effect.power` a Wonder stage can grant (keys match the
    // `power` strings used in WONDERS below). Kept as data so the UI never hard-codes rule text.
    WONDER_POWERS: {
        produceRawChoice: "Each turn, produce 1 raw material of your choice (Stone/Clay/Wood/Ore). Neighbours cannot buy it.",
        produceManufacturedChoice: "Each turn, produce 1 manufactured good of your choice (Glass/Loom/Papyrus). Neighbours cannot buy it.",
        extraScienceSymbol: "At the end of the game, gain an extra scientific symbol of your choice.",
        freeBuildPerAge: "Once per Age, construct a structure from your hand for free.",
        discardPileBuild: "Look through every card discarded since the start of the game, pick one, and build it for free.",
        lastCardAlternative: "Play the 7th card of each Age instead of discarding it (build it, discard it for 3 coins, or use it on your Wonder).",
        cheapRawTrade: "Buy raw materials from both neighbouring cities for 1 coin instead of 2.",
        copyNeighborGuild: "At the end of the game, copy one Guild (purple card) built by either neighbouring city.",
    },
    // The seven Wonder boards, transcribed from the board scans and rule text in
    // docs/wonders_boards/*.png. Each board has a starting `resource` (produced free from turn 1,
    // and purchasable by neighbours like any other production) and two playable faces:
    // `sides.A` (the simple face) and `sides.B` (the advanced face). Every side is a list of
    // stages built strictly left-to-right, each `{ cost, effect }`; `effect` may carry any of
    // `vp` / `coins` / `shields` / `power` (see WONDER_POWERS above). Gizah's B face is the one
    // board with 4 stages — nothing may assume a fixed stage count.
    //
    // Unlike CARDS below, this data *is* transcribed from the physical boards, not placeholder.
    WONDERS: [
        {
            id: "gizah", name: "Gizah", emoji: "🔺", resource: "stone",
            sides: {
                A: {
                    summary: "No special ability — the three stages are worth 3, 5 and 7 victory points.",
                    stages: [
                        { cost: { stone: 2 }, effect: { vp: 3 } },
                        { cost: { wood: 3 }, effect: { vp: 5 } },
                        { cost: { stone: 4 }, effect: { vp: 7 } },
                    ],
                },
                B: {
                    summary: "Built in 4 stages worth 3, 5, 5 and 7 victory points — 20 points in total.",
                    stages: [
                        { cost: { wood: 2 }, effect: { vp: 3 } },
                        { cost: { stone: 3 }, effect: { vp: 5 } },
                        { cost: { clay: 3 }, effect: { vp: 5 } },
                        { cost: { stone: 4, papyrus: 1 }, effect: { vp: 7 } },
                    ],
                },
            },
        },
        {
            id: "rhodos", name: "Rhodos", emoji: "🗿", resource: "ore",
            sides: {
                A: {
                    summary: "The second stage adds 2 Shields to your strength in every conflict resolution.",
                    stages: [
                        { cost: { wood: 2 }, effect: { vp: 3 } },
                        { cost: { clay: 3 }, effect: { shields: 2 } },
                        { cost: { ore: 4 }, effect: { vp: 7 } },
                    ],
                },
                B: {
                    summary: "The Colossus is built in only 2 stages, each worth 1 Shield, coins and victory points.",
                    stages: [
                        { cost: { stone: 3 }, effect: { shields: 1, coins: 3, vp: 3 } },
                        { cost: { ore: 4 }, effect: { shields: 1, coins: 4, vp: 4 } },
                    ],
                },
            },
        },
        {
            id: "ephesos", name: "Ephesos", emoji: "🛕", resource: "papyrus",
            sides: {
                A: {
                    summary: "The second stage pays 9 coins from the bank, once, as soon as it is built.",
                    stages: [
                        { cost: { stone: 2 }, effect: { vp: 3 } },
                        { cost: { wood: 2 }, effect: { coins: 9 } },
                        { cost: { papyrus: 2 }, effect: { vp: 7 } },
                    ],
                },
                B: {
                    summary: "Every stage pays 4 coins from the bank, once, as soon as it is built.",
                    stages: [
                        { cost: { stone: 2 }, effect: { vp: 2, coins: 4 } },
                        { cost: { wood: 2 }, effect: { vp: 3, coins: 4 } },
                        { cost: { papyrus: 1, loom: 1, glass: 1 }, effect: { vp: 5, coins: 4 } },
                    ],
                },
            },
        },
        {
            id: "babylon", name: "Babylon", emoji: "🌳", resource: "clay",
            sides: {
                A: {
                    summary: "The second stage grants an extra scientific symbol, chosen at the end of the game.",
                    stages: [
                        { cost: { clay: 2 }, effect: { vp: 3 } },
                        { cost: { wood: 3 }, effect: { power: "extraScienceSymbol" } },
                        { cost: { clay: 4 }, effect: { vp: 7 } },
                    ],
                },
                B: {
                    summary: "The second stage lets you play the 7th card of each Age; the third grants a scientific symbol of your choice.",
                    stages: [
                        { cost: { loom: 1, clay: 1 }, effect: { vp: 3 } },
                        { cost: { glass: 1, wood: 2 }, effect: { power: "lastCardAlternative" } },
                        { cost: { clay: 4, papyrus: 1 }, effect: { power: "extraScienceSymbol" } },
                    ],
                },
            },
        },
        {
            id: "olympia", name: "Olympia", emoji: "🏟️", resource: "wood",
            sides: {
                A: {
                    summary: "The second stage lets you build one structure for free, once per Age.",
                    stages: [
                        { cost: { wood: 2 }, effect: { vp: 3 } },
                        { cost: { stone: 2 }, effect: { power: "freeBuildPerAge" } },
                        { cost: { ore: 2 }, effect: { vp: 7 } },
                    ],
                },
                B: {
                    summary: "Cheap raw materials from both neighbours, then 5 VP, then a copy of a neighbouring Guild.",
                    stages: [
                        { cost: { wood: 2 }, effect: { power: "cheapRawTrade" } },
                        { cost: { stone: 2 }, effect: { vp: 5 } },
                        { cost: { loom: 1, ore: 2 }, effect: { power: "copyNeighborGuild" } },
                    ],
                },
            },
        },
        {
            id: "halikarnassos", name: "Halikarnassos", emoji: "⚰️", resource: "loom",
            sides: {
                A: {
                    summary: "The second stage lets you build one card from the discard pile for free.",
                    stages: [
                        { cost: { clay: 2 }, effect: { vp: 3 } },
                        { cost: { ore: 3 }, effect: { power: "discardPileBuild" } },
                        { cost: { loom: 2 }, effect: { vp: 7 } },
                    ],
                },
                B: {
                    summary: "Every stage lets you build another card from the discard pile for free.",
                    stages: [
                        { cost: { ore: 2 }, effect: { vp: 2, power: "discardPileBuild" } },
                        { cost: { clay: 3 }, effect: { vp: 1, power: "discardPileBuild" } },
                        { cost: { glass: 1, papyrus: 1, loom: 1 }, effect: { power: "discardPileBuild" } },
                    ],
                },
            },
        },
        {
            id: "alexandria", name: "Alexandria", emoji: "🗼", resource: "glass",
            sides: {
                A: {
                    summary: "The second stage produces one raw material of your choice every turn.",
                    stages: [
                        { cost: { stone: 2 }, effect: { vp: 3 } },
                        { cost: { ore: 2 }, effect: { power: "produceRawChoice" } },
                        { cost: { glass: 2 }, effect: { vp: 7 } },
                    ],
                },
                B: {
                    summary: "A raw material of your choice each turn, then a manufactured good of your choice, then 7 VP.",
                    stages: [
                        { cost: { clay: 2 }, effect: { power: "produceRawChoice" } },
                        { cost: { wood: 2 }, effect: { power: "produceManufacturedChoice" } },
                        { cost: { stone: 3 }, effect: { vp: 7 } },
                    ],
                },
            },
        },
    ],
    // Card pool — sample content, sized to deal 3 Ages x 7 cards x up to 7 players. The base pool
    // (`playerCount: 3` or `4`) is 28 cards per Age I/II and 22 non-Guild + 10 Guild for Age III,
    // matching docs/rules.md's "players + 2" rule for how many Guilds get kept at the table. Each
    // Age's "extra content (5-7 players)" block (`playerCount: 5`/`6`/`7`) layers in exactly enough
    // additional cards that every offered player count still deals 7×players cards per Age — see
    // SUPPORTED_PLAYER_COUNTS's comment above for the exact accounting. This is NOT the
    // authoritative ~90-card physical deck (exact per-card costs/effects and player-count-scaled
    // counts are box-sourced and not transcribed) — names, costs and VP values here are an original
    // placeholder design good enough to play the real rules against, for the base pool and the
    // extra-content blocks alike. Guild scoring rules, the Age II/III commerce-card mechanics, and
    // the science-scoring formula *are* transcribed from docs/rules.md and should be accurate.
    // Replace/expand via admin/index.html once real content is authored.
    CARDS: [
        // ---- Age I ----
        { id: "lumber-yard", name: "Lumber Yard", emoji: "🪵", age: 1, type: "basic",
            cost: {}, produces: ["wood"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Produces 1 Wood.", chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "forest-cave", name: "Forest Cave", emoji: "🌲", age: 1, type: "basic",
            cost: {}, produces: ["wood"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Produces 1 Wood.", chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "ore-vein", name: "Ore Vein", emoji: "⛏️", age: 1, type: "basic",
            cost: {}, produces: ["ore"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Produces 1 Ore.", chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "mine", name: "Mine", emoji: "⛰️", age: 1, type: "basic",
            cost: {}, produces: ["ore"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Produces 1 Ore.", chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "clay-pool", name: "Clay Pool", emoji: "🧱", age: 1, type: "basic",
            cost: {}, produces: ["clay"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Produces 1 Clay.", chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "clay-pit", name: "Clay Pit", emoji: "🧱", age: 1, type: "basic",
            cost: {}, produces: ["clay"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Produces 1 Clay.", chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "stone-pit", name: "Stone Pit", emoji: "🪨", age: 1, type: "basic",
            cost: {}, produces: ["stone"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Produces 1 Stone.", chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "quarry", name: "Quarry", emoji: "🪨", age: 1, type: "basic",
            cost: {}, produces: ["stone"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Produces 1 Stone.", chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "glassworks", name: "Glassworks", emoji: "🔷", age: 1, type: "manufactured",
            cost: {}, produces: ["glass"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Produces 1 Glass.", chainFrom: [], chainTo: ["stained-glass-works"], playerCount: 3 },
        { id: "press", name: "Press", emoji: "📜", age: 1, type: "manufactured",
            cost: {}, produces: ["papyrus"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Produces 1 Papyrus.", chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "loom-house", name: "Loom House", emoji: "🧵", age: 1, type: "manufactured",
            cost: {}, produces: ["loom"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Produces 1 Loom.", chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "baths", name: "Baths", emoji: "🛁", age: 1, type: "civilian",
            cost: { stone: 1 }, produces: [], producesChoice: false, vp: 3, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Worth 3 VP.", chainFrom: [], chainTo: ["aqueduct"], playerCount: 3 },
        { id: "altar", name: "Altar", emoji: "⛩️", age: 1, type: "civilian",
            cost: {}, produces: [], producesChoice: false, vp: 2, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Worth 2 VP.", chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "theater", name: "Theater", emoji: "🎭", age: 1, type: "civilian",
            cost: {}, produces: [], producesChoice: false, vp: 2, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Worth 2 VP.", chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "well", name: "Well", emoji: "⛲", age: 1, type: "civilian",
            cost: { wood: 1 }, produces: [], producesChoice: false, vp: 3, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Worth 3 VP.", chainFrom: [], chainTo: [], playerCount: 4 },
        { id: "shrine", name: "Shrine", emoji: "⛪", age: 1, type: "civilian",
            cost: {}, produces: [], producesChoice: false, vp: 2, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Worth 2 VP.", chainFrom: [], chainTo: ["temple"], playerCount: 3 },
        { id: "statue-garden", name: "Statue Garden", emoji: "🌷", age: 1, type: "civilian",
            cost: { clay: 1 }, produces: [], producesChoice: false, vp: 3, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Worth 3 VP.", chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "plaza", name: "Plaza", emoji: "🏙️", age: 1, type: "civilian",
            cost: { ore: 1 }, produces: [], producesChoice: false, vp: 3, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Worth 3 VP.", chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "scriptorium", name: "Scriptorium", emoji: "📚", age: 1, type: "scientific",
            cost: { papyrus: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: "tablet", effect: "Grants a Tablet science symbol.", chainFrom: [], chainTo: ["courthouse"], playerCount: 3 },
        { id: "workshop", name: "Workshop", emoji: "🧭", age: 1, type: "scientific",
            cost: { glass: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: "compass", effect: "Grants a Compass science symbol.", chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "apothecary", name: "Apothecary", emoji: "⚙️", age: 1, type: "scientific",
            cost: { loom: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: "gear", effect: "Grants a Gear science symbol.", chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "tavern", name: "Tavern", emoji: "🍺", age: 1, type: "commercial",
            cost: {}, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 5,
            science: null, effect: "Gives 5 coins when built.", chainFrom: [], chainTo: [], playerCount: 4 },
        { id: "market", name: "Market", emoji: "🛒", age: 1, type: "commercial",
            cost: {}, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 3,
            science: null, effect: "Gives 3 coins when built.", chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "trading-post", name: "Trading Post", emoji: "🤝", age: 1, type: "commercial",
            cost: {}, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 3,
            science: null, effect: "Gives 3 coins when built. Buy raw materials from either neighbour for 1 coin instead of 2.",
            chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "caravanserai", name: "Caravanserai", emoji: "🐫", age: 1, type: "commercial",
            cost: {}, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 3,
            science: null, effect: "Gives 3 coins when built. Buy manufactured goods from either neighbour for 1 coin instead of 2.",
            chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "stockade", name: "Stockade", emoji: "🛡️", age: 1, type: "military",
            cost: { wood: 1 }, produces: [], producesChoice: false, vp: 0, shields: 1, coinsOnPlay: 0,
            science: null, effect: "Grants 1 Shield.", chainFrom: [], chainTo: ["walls"], playerCount: 3 },
        { id: "garrison", name: "Garrison", emoji: "🗡️", age: 1, type: "military",
            cost: { ore: 1 }, produces: [], producesChoice: false, vp: 0, shields: 1, coinsOnPlay: 0,
            science: null, effect: "Grants 1 Shield.", chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "barracks", name: "Barracks", emoji: "⚔️", age: 1, type: "military",
            cost: { clay: 1 }, produces: [], producesChoice: false, vp: 0, shields: 1, coinsOnPlay: 0,
            science: null, effect: "Grants 1 Shield.", chainFrom: [], chainTo: ["archery-range"], playerCount: 3 },
        // ---- Age I extra content (5-7 players) ----
        { id: "lumber-camp", name: "Lumber Camp", emoji: "🪵", age: 1, type: "basic",
            cost: {}, produces: ["wood"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Produces 1 Wood.", chainFrom: [], chainTo: [], playerCount: 5 },
        { id: "copper-mine", name: "Copper Mine", emoji: "⛏️", age: 1, type: "basic",
            cost: {}, produces: ["ore"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Produces 1 Ore.", chainFrom: [], chainTo: [], playerCount: 5 },
        { id: "clay-flats", name: "Clay Flats", emoji: "🧱", age: 1, type: "basic",
            cost: {}, produces: ["clay"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Produces 1 Clay.", chainFrom: [], chainTo: [], playerCount: 5 },
        { id: "loom-croft", name: "Loom Croft", emoji: "🧵", age: 1, type: "manufactured",
            cost: {}, produces: ["loom"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Produces 1 Loom.", chainFrom: [], chainTo: [], playerCount: 5 },
        { id: "meeting-hall", name: "Meeting Hall", emoji: "🏘️", age: 1, type: "civilian",
            cost: {}, produces: [], producesChoice: false, vp: 2, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Worth 2 VP.", chainFrom: [], chainTo: [], playerCount: 5 },
        { id: "scholars-nook", name: "Scholars' Nook", emoji: "📚", age: 1, type: "scientific",
            cost: { papyrus: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: "tablet", effect: "Grants a Tablet science symbol.", chainFrom: [], chainTo: [], playerCount: 5 },
        { id: "watch-post", name: "Watch Post", emoji: "🛡️", age: 1, type: "military",
            cost: { wood: 1 }, produces: [], producesChoice: false, vp: 0, shields: 1, coinsOnPlay: 0,
            science: null, effect: "Grants 1 Shield.", chainFrom: [], chainTo: [], playerCount: 5 },
        { id: "granite-pit", name: "Granite Pit", emoji: "🪨", age: 1, type: "basic",
            cost: {}, produces: ["stone"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Produces 1 Stone.", chainFrom: [], chainTo: [], playerCount: 6 },
        { id: "birch-grove", name: "Birch Grove", emoji: "🪵", age: 1, type: "basic",
            cost: {}, produces: ["wood"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Produces 1 Wood.", chainFrom: [], chainTo: [], playerCount: 6 },
        { id: "tin-vein", name: "Tin Vein", emoji: "⛏️", age: 1, type: "basic",
            cost: {}, produces: ["ore"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Produces 1 Ore.", chainFrom: [], chainTo: [], playerCount: 6 },
        { id: "glass-shed", name: "Glass Shed", emoji: "🔷", age: 1, type: "manufactured",
            cost: {}, produces: ["glass"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Produces 1 Glass.", chainFrom: [], chainTo: [], playerCount: 6 },
        { id: "public-bath", name: "Public Bath", emoji: "🛁", age: 1, type: "civilian",
            cost: {}, produces: [], producesChoice: false, vp: 2, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Worth 2 VP.", chainFrom: [], chainTo: [], playerCount: 6 },
        { id: "survey-post", name: "Survey Post", emoji: "🧭", age: 1, type: "scientific",
            cost: { glass: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: "compass", effect: "Grants a Compass science symbol.", chainFrom: [], chainTo: [], playerCount: 6 },
        { id: "palisade", name: "Palisade", emoji: "🛡️", age: 1, type: "military",
            cost: { ore: 1 }, produces: [], producesChoice: false, vp: 0, shields: 1, coinsOnPlay: 0,
            science: null, effect: "Grants 1 Shield.", chainFrom: [], chainTo: [], playerCount: 6 },
        { id: "clay-terrace", name: "Clay Terrace", emoji: "🧱", age: 1, type: "basic",
            cost: {}, produces: ["clay"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Produces 1 Clay.", chainFrom: [], chainTo: [], playerCount: 7 },
        { id: "pine-camp", name: "Pine Camp", emoji: "🪵", age: 1, type: "basic",
            cost: {}, produces: ["wood"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Produces 1 Wood.", chainFrom: [], chainTo: [], playerCount: 7 },
        { id: "quartz-mine", name: "Quartz Mine", emoji: "⛏️", age: 1, type: "basic",
            cost: {}, produces: ["ore"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Produces 1 Ore.", chainFrom: [], chainTo: [], playerCount: 7 },
        { id: "papyrus-hut", name: "Papyrus Hut", emoji: "📜", age: 1, type: "manufactured",
            cost: {}, produces: ["papyrus"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Produces 1 Papyrus.", chainFrom: [], chainTo: [], playerCount: 7 },
        { id: "garden-shrine", name: "Garden Shrine", emoji: "⛩️", age: 1, type: "civilian",
            cost: {}, produces: [], producesChoice: false, vp: 2, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Worth 2 VP.", chainFrom: [], chainTo: [], playerCount: 7 },
        { id: "archive-room", name: "Archive Room", emoji: "⚙️", age: 1, type: "scientific",
            cost: { loom: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: "gear", effect: "Grants a Gear science symbol.", chainFrom: [], chainTo: [], playerCount: 7 },
        { id: "sentry-tower", name: "Sentry Tower", emoji: "⚔️", age: 1, type: "military",
            cost: { clay: 1 }, produces: [], producesChoice: false, vp: 0, shields: 1, coinsOnPlay: 0,
            science: null, effect: "Grants 1 Shield.", chainFrom: [], chainTo: [], playerCount: 7 },
        // ---- Age II ----
        { id: "sawmill", name: "Sawmill", emoji: "🪚", age: 2, type: "basic",
            cost: {}, produces: ["wood"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Produces 2 Wood.", produceCount: 2, chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "foundry", name: "Foundry", emoji: "⛏️", age: 2, type: "basic",
            cost: {}, produces: ["ore"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Produces 2 Ore.", produceCount: 2, chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "brickyard", name: "Brickyard", emoji: "🧱", age: 2, type: "basic",
            cost: {}, produces: ["clay"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Produces 2 Clay.", produceCount: 2, chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "shelf-quarry", name: "Shelf Quarry", emoji: "🪨", age: 2, type: "basic",
            cost: {}, produces: ["stone"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Produces 2 Stone.", produceCount: 2, chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "stained-glass-works", name: "Stained Glass Works", emoji: "🔷", age: 2, type: "manufactured",
            cost: {}, produces: ["glass"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Produces 1 Glass.", chainFrom: ["glassworks"], chainTo: [], playerCount: 3 },
        { id: "papyrus-mill", name: "Papyrus Mill", emoji: "📜", age: 2, type: "manufactured",
            cost: {}, produces: ["papyrus"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Produces 1 Papyrus.", chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "loom-shed", name: "Loom Shed", emoji: "🧵", age: 2, type: "manufactured",
            cost: {}, produces: ["loom"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Produces 1 Loom.", chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "caravan", name: "Caravan", emoji: "🚚", age: 2, type: "basic",
            cost: {}, produces: ["clay", "ore", "stone", "wood"], producesChoice: true, vp: 0, shields: 0,
            coinsOnPlay: 0, science: null, effect: "Produces 1 of your choice: Clay, Ore, Stone, or Wood.",
            chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "bazaar", name: "Bazaar", emoji: "🏺", age: 2, type: "manufactured",
            cost: {}, produces: ["glass", "loom", "papyrus"], producesChoice: true, vp: 0, shields: 0,
            coinsOnPlay: 0, science: null, effect: "Produces 1 of your choice: Glass, Loom, or Papyrus.",
            chainFrom: [], chainTo: [], playerCount: 4 },
        { id: "aqueduct", name: "Aqueduct", emoji: "🌉", age: 2, type: "civilian",
            cost: { stone: 2 }, produces: [], producesChoice: false, vp: 5, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Worth 5 VP.", chainFrom: ["baths"], chainTo: [], playerCount: 3 },
        { id: "temple", name: "Temple", emoji: "🏯", age: 2, type: "civilian",
            cost: { wood: 1, clay: 1 }, produces: [], producesChoice: false, vp: 4, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Worth 4 VP.", chainFrom: ["shrine"], chainTo: ["grand-temple"], playerCount: 3 },
        { id: "statue", name: "Statue", emoji: "🗽", age: 2, type: "civilian",
            cost: { ore: 2 }, produces: [], producesChoice: false, vp: 4, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Worth 4 VP.", chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "courtyard", name: "Courtyard", emoji: "🏘️", age: 2, type: "civilian",
            cost: { clay: 2 }, produces: [], producesChoice: false, vp: 4, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Worth 4 VP.", chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "gardens", name: "Gardens", emoji: "🌺", age: 2, type: "civilian",
            cost: { clay: 2 }, produces: [], producesChoice: false, vp: 5, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Worth 5 VP.", chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "senate", name: "Senate", emoji: "🏛️", age: 2, type: "civilian",
            cost: { wood: 1, stone: 1, ore: 1 }, produces: [], producesChoice: false, vp: 6, shields: 0,
            coinsOnPlay: 0, science: null, effect: "Worth 6 VP.", chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "forum-hall", name: "Forum Hall", emoji: "🏢", age: 2, type: "civilian",
            cost: { clay: 2 }, produces: [], producesChoice: false, vp: 4, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Worth 4 VP.", chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "amphitheater", name: "Amphitheater", emoji: "🎪", age: 2, type: "civilian",
            cost: { stone: 2 }, produces: [], producesChoice: false, vp: 5, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Worth 5 VP.", chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "courthouse", name: "Courthouse", emoji: "📚", age: 2, type: "scientific",
            cost: { loom: 2 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: "tablet", effect: "Grants a Tablet science symbol.", chainFrom: ["scriptorium"], chainTo: ["university-of-science"], playerCount: 3 },
        { id: "observatory", name: "Observatory", emoji: "🧭", age: 2, type: "scientific",
            cost: { ore: 2 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: "compass", effect: "Grants a Compass science symbol.", chainFrom: [], chainTo: ["observatory-tower"], playerCount: 3 },
        { id: "pharmacy", name: "Pharmacy", emoji: "⚙️", age: 2, type: "scientific",
            cost: { papyrus: 2 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: "gear", effect: "Grants a Gear science symbol.", chainFrom: [], chainTo: ["lodge"], playerCount: 3 },
        { id: "customs-house", name: "Customs House", emoji: "🏦", age: 2, type: "commercial",
            cost: {}, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 6,
            science: null, effect: "Gives 6 coins when built.", chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "forum-market", name: "Forum Market", emoji: "💰", age: 2, type: "commercial",
            cost: {}, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Worth 1 coin per Raw Material card built in your city and in the 2 neighbouring cities.",
            chainFrom: [], chainTo: [], coinsPerCardType: { cardType: "basic", per: 1, scope: "selfAndNeighbors" }, playerCount: 3 },
        { id: "guild-exchange", name: "Guild Exchange", emoji: "💱", age: 2, type: "commercial",
            cost: {}, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Worth 2 coins per Manufactured Good card built in your city and in the 2 neighbouring cities.",
            chainFrom: [], chainTo: [], coinsPerCardType: { cardType: "manufactured", per: 2, scope: "selfAndNeighbors" }, playerCount: 3 },
        { id: "dockyard", name: "Dockyard", emoji: "⚓", age: 2, type: "commercial",
            cost: {}, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 6,
            science: null, effect: "Gives 6 coins when built.", chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "bank", name: "Bank", emoji: "🏦", age: 2, type: "commercial",
            cost: {}, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 8,
            science: null, effect: "Gives 8 coins when built.", chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "walls", name: "Walls", emoji: "🧱", age: 2, type: "military",
            cost: { stone: 2 }, produces: [], producesChoice: false, vp: 0, shields: 2, coinsOnPlay: 0,
            science: null, effect: "Grants 2 Shields.", chainFrom: ["stockade"], chainTo: ["siege-camp"], playerCount: 3 },
        { id: "archery-range", name: "Archery Range", emoji: "🏹", age: 2, type: "military",
            cost: { wood: 2 }, produces: [], producesChoice: false, vp: 0, shields: 2, coinsOnPlay: 0,
            science: null, effect: "Grants 2 Shields.", chainFrom: ["barracks"], chainTo: ["citadel"], playerCount: 3 },
        { id: "training-ground", name: "Training Ground", emoji: "🎯", age: 2, type: "military",
            cost: { ore: 1, wood: 1 }, produces: [], producesChoice: false, vp: 0, shields: 2, coinsOnPlay: 0,
            science: null, effect: "Grants 2 Shields.", chainFrom: [], chainTo: [], playerCount: 4 },
        // ---- Age II extra content (5-7 players) ----
        { id: "log-mill", name: "Log Mill", emoji: "🪚", age: 2, type: "basic",
            cost: {}, produces: ["wood"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Produces 2 Wood.", produceCount: 2, chainFrom: [], chainTo: [], playerCount: 5 },
        { id: "smeltery", name: "Smeltery", emoji: "⛏️", age: 2, type: "basic",
            cost: {}, produces: ["ore"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Produces 2 Ore.", produceCount: 2, chainFrom: [], chainTo: [], playerCount: 5 },
        { id: "clay-works", name: "Clay Works", emoji: "🧱", age: 2, type: "basic",
            cost: {}, produces: ["clay"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Produces 2 Clay.", produceCount: 2, chainFrom: [], chainTo: [], playerCount: 5 },
        { id: "dye-mill", name: "Dye Mill", emoji: "🧵", age: 2, type: "manufactured",
            cost: {}, produces: ["loom"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Produces 1 Loom.", chainFrom: [], chainTo: [], playerCount: 5 },
        { id: "plaza-hall", name: "Plaza Hall", emoji: "🏘️", age: 2, type: "civilian",
            cost: { clay: 2 }, produces: [], producesChoice: false, vp: 4, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Worth 4 VP.", chainFrom: [], chainTo: [], playerCount: 5 },
        { id: "study-hall", name: "Study Hall", emoji: "📚", age: 2, type: "scientific",
            cost: { loom: 2 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: "tablet", effect: "Grants a Tablet science symbol.", chainFrom: [], chainTo: [], playerCount: 5 },
        { id: "garrison-wall", name: "Garrison Wall", emoji: "🧱", age: 2, type: "military",
            cost: { stone: 2 }, produces: [], producesChoice: false, vp: 0, shields: 2, coinsOnPlay: 0,
            science: null, effect: "Grants 2 Shields.", chainFrom: [], chainTo: [], playerCount: 5 },
        { id: "quarry-camp", name: "Quarry Camp", emoji: "🪨", age: 2, type: "basic",
            cost: {}, produces: ["stone"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Produces 2 Stone.", produceCount: 2, chainFrom: [], chainTo: [], playerCount: 6 },
        { id: "grove-mill", name: "Grove Mill", emoji: "🪚", age: 2, type: "basic",
            cost: {}, produces: ["wood"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Produces 2 Wood.", produceCount: 2, chainFrom: [], chainTo: [], playerCount: 6 },
        { id: "ore-works", name: "Ore Works", emoji: "⛏️", age: 2, type: "basic",
            cost: {}, produces: ["ore"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Produces 2 Ore.", produceCount: 2, chainFrom: [], chainTo: [], playerCount: 6 },
        { id: "glass-foundry", name: "Glass Foundry", emoji: "🔷", age: 2, type: "manufactured",
            cost: {}, produces: ["glass"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Produces 1 Glass.", chainFrom: [], chainTo: [], playerCount: 6 },
        { id: "civic-hall", name: "Civic Hall", emoji: "🗽", age: 2, type: "civilian",
            cost: { ore: 2 }, produces: [], producesChoice: false, vp: 4, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Worth 4 VP.", chainFrom: [], chainTo: [], playerCount: 6 },
        { id: "watch-tower", name: "Watch Tower", emoji: "🧭", age: 2, type: "scientific",
            cost: { ore: 2 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: "compass", effect: "Grants a Compass science symbol.", chainFrom: [], chainTo: [], playerCount: 6 },
        { id: "rampart", name: "Rampart", emoji: "🏹", age: 2, type: "military",
            cost: { wood: 2 }, produces: [], producesChoice: false, vp: 0, shields: 2, coinsOnPlay: 0,
            science: null, effect: "Grants 2 Shields.", chainFrom: [], chainTo: [], playerCount: 6 },
        { id: "silt-pit", name: "Silt Pit", emoji: "🧱", age: 2, type: "basic",
            cost: {}, produces: ["clay"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Produces 2 Clay.", produceCount: 2, chainFrom: [], chainTo: [], playerCount: 7 },
        { id: "pine-mill", name: "Pine Mill", emoji: "🪚", age: 2, type: "basic",
            cost: {}, produces: ["wood"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Produces 2 Wood.", produceCount: 2, chainFrom: [], chainTo: [], playerCount: 7 },
        { id: "stone-works", name: "Stone Works", emoji: "🪨", age: 2, type: "basic",
            cost: {}, produces: ["stone"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Produces 2 Stone.", produceCount: 2, chainFrom: [], chainTo: [], playerCount: 7 },
        { id: "papyrus-hall", name: "Papyrus Hall", emoji: "📜", age: 2, type: "manufactured",
            cost: {}, produces: ["papyrus"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Produces 1 Papyrus.", chainFrom: [], chainTo: [], playerCount: 7 },
        { id: "forum-annex", name: "Forum Annex", emoji: "🏢", age: 2, type: "civilian",
            cost: { clay: 2 }, produces: [], producesChoice: false, vp: 4, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Worth 4 VP.", chainFrom: [], chainTo: [], playerCount: 7 },
        { id: "workshop-hall", name: "Workshop Hall", emoji: "⚙️", age: 2, type: "scientific",
            cost: { papyrus: 2 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: "gear", effect: "Grants a Gear science symbol.", chainFrom: [], chainTo: [], playerCount: 7 },
        { id: "training-yard", name: "Training Yard", emoji: "🎯", age: 2, type: "military",
            cost: { ore: 1, wood: 1 }, produces: [], producesChoice: false, vp: 0, shields: 2, coinsOnPlay: 0,
            science: null, effect: "Grants 2 Shields.", chainFrom: [], chainTo: [], playerCount: 7 },
        // ---- Age III (non-Guild) ----
        { id: "pantheon", name: "Pantheon", emoji: "⛩️", age: 3, type: "civilian",
            cost: { clay: 2, loom: 1, papyrus: 1 }, produces: [], producesChoice: false, vp: 8, shields: 0,
            coinsOnPlay: 0, science: null, effect: "Worth 8 VP.", chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "gardens-palace", name: "Gardens Palace", emoji: "🏞️", age: 3, type: "civilian",
            cost: { clay: 2, wood: 2 }, produces: [], producesChoice: false, vp: 7, shields: 0,
            coinsOnPlay: 0, science: null, effect: "Worth 7 VP.", chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "town-hall", name: "Town Hall", emoji: "🏤", age: 3, type: "civilian",
            cost: { stone: 3, glass: 1 }, produces: [], producesChoice: false, vp: 7, shields: 0,
            coinsOnPlay: 0, science: null, effect: "Worth 7 VP.", chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "palace", name: "Palace", emoji: "🏰", age: 3, type: "civilian",
            cost: { stone: 2, ore: 1, glass: 1 }, produces: [], producesChoice: false, vp: 8, shields: 0,
            coinsOnPlay: 0, science: null, effect: "Worth 8 VP.", chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "obelisk", name: "Obelisk", emoji: "🗿", age: 3, type: "civilian",
            cost: { stone: 2, wood: 1 }, produces: [], producesChoice: false, vp: 6, shields: 0,
            coinsOnPlay: 0, science: null, effect: "Worth 6 VP.", chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "senate-hall", name: "Senate Hall", emoji: "🏛️", age: 3, type: "civilian",
            cost: { ore: 2, loom: 1 }, produces: [], producesChoice: false, vp: 6, shields: 0,
            coinsOnPlay: 0, science: null, effect: "Worth 6 VP.", chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "grand-arena", name: "Grand Arena", emoji: "🏟️", age: 3, type: "civilian",
            cost: { stone: 3 }, produces: [], producesChoice: false, vp: 6, shields: 0,
            coinsOnPlay: 0, science: null, effect: "Worth 6 VP.", chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "university", name: "University", emoji: "🎓", age: 3, type: "civilian",
            cost: { wood: 2, papyrus: 1 }, produces: [], producesChoice: false, vp: 5, shields: 0,
            coinsOnPlay: 0, science: null, effect: "Worth 5 VP.", chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "library", name: "Library", emoji: "📖", age: 3, type: "civilian",
            cost: { stone: 1, loom: 1, papyrus: 1 }, produces: [], producesChoice: false, vp: 6, shields: 0,
            coinsOnPlay: 0, science: null, effect: "Worth 6 VP.", chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "monument", name: "Monument", emoji: "🗼", age: 3, type: "civilian",
            cost: { clay: 2, stone: 1 }, produces: [], producesChoice: false, vp: 6, shields: 0,
            coinsOnPlay: 0, science: null, effect: "Worth 6 VP.", chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "sanctuary", name: "Sanctuary", emoji: "🕍", age: 3, type: "civilian",
            cost: { glass: 1, loom: 1, papyrus: 1 }, produces: [], producesChoice: false, vp: 7, shields: 0,
            coinsOnPlay: 0, science: null, effect: "Worth 7 VP.", chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "grand-temple", name: "Grand Temple", emoji: "🏯", age: 3, type: "civilian",
            cost: { clay: 1, glass: 1, loom: 1 }, produces: [], producesChoice: false, vp: 7, shields: 0,
            coinsOnPlay: 0, science: null, effect: "Worth 7 VP.", chainFrom: ["temple"], chainTo: [], playerCount: 3 },
        { id: "university-of-science", name: "University of Science", emoji: "📚", age: 3, type: "scientific",
            cost: { papyrus: 2, loom: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0,
            coinsOnPlay: 0, science: "tablet", effect: "Grants a Tablet science symbol.",
            chainFrom: ["courthouse"], chainTo: [], playerCount: 3 },
        { id: "observatory-tower", name: "Observatory Tower", emoji: "🧭", age: 3, type: "scientific",
            cost: { ore: 2, glass: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0,
            coinsOnPlay: 0, science: "compass", effect: "Grants a Compass science symbol.",
            chainFrom: ["observatory"], chainTo: [], playerCount: 3 },
        { id: "lodge", name: "Lodge", emoji: "⚙️", age: 3, type: "scientific",
            cost: { loom: 2, clay: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0,
            coinsOnPlay: 0, science: "gear", effect: "Grants a Gear science symbol.",
            chainFrom: ["pharmacy"], chainTo: [], playerCount: 3 },
        { id: "arsenal", name: "Arsenal", emoji: "🏹", age: 3, type: "commercial",
            cost: {}, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0, science: null,
            effect: "Gives 3 coins per Wonder stage built in its home city when played. At game end, worth 1 VP per Wonder stage built in its home city.",
            chainFrom: [], chainTo: [],
            coinsPerWonderStage: { per: 3, scope: "self" }, vpPerWonderStage: { per: 1, scope: "self" }, playerCount: 3 },
        { id: "lighthouse", name: "Lighthouse", emoji: "🚨", age: 3, type: "commercial",
            cost: {}, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0, science: null,
            effect: "Gives 1 coin per Raw Material card in your city when played. At game end, worth 1 VP for each Raw Material card present in your city.",
            chainFrom: [], chainTo: [],
            coinsPerCardType: { cardType: "basic", per: 1, scope: "self" }, vpPerCardType: { cardType: "basic", per: 1, scope: "self" }, playerCount: 3 },
        { id: "haven", name: "Haven", emoji: "⚓", age: 3, type: "commercial",
            cost: {}, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0, science: null,
            effect: "Gives 2 coins per Manufactured Good card in your city when played. At game end, worth 2 VP for each Manufactured Good card present in your city.",
            chainFrom: [], chainTo: [],
            coinsPerCardType: { cardType: "manufactured", per: 2, scope: "self" }, vpPerCardType: { cardType: "manufactured", per: 2, scope: "self" }, playerCount: 3 },
        { id: "chamber-of-commerce", name: "Chamber of Commerce", emoji: "🏢", age: 3, type: "commercial",
            cost: {}, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0, science: null,
            effect: "Gives 1 coin per Commercial card in your city (including itself) when played. At game end, worth 1 VP for each Commercial card present in your city.",
            chainFrom: [], chainTo: [],
            coinsPerCardType: { cardType: "commercial", per: 1, scope: "self", includeSelf: true },
            vpPerCardType: { cardType: "commercial", per: 1, scope: "self", includeSelf: true }, playerCount: 3 },
        { id: "fortress", name: "Fortress", emoji: "🏯", age: 3, type: "military",
            cost: { stone: 2, ore: 1 }, produces: [], producesChoice: false, vp: 0, shields: 3, coinsOnPlay: 0,
            science: null, effect: "Grants 3 Shields.", chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "siege-camp", name: "Siege Camp", emoji: "🏕️", age: 3, type: "military",
            cost: { wood: 2, ore: 1 }, produces: [], producesChoice: false, vp: 0, shields: 3, coinsOnPlay: 0,
            science: null, effect: "Grants 3 Shields.", chainFrom: ["walls"], chainTo: [], playerCount: 3 },
        { id: "citadel", name: "Citadel", emoji: "🏰", age: 3, type: "military",
            cost: { stone: 3 }, produces: [], producesChoice: false, vp: 0, shields: 3, coinsOnPlay: 0,
            science: null, effect: "Grants 3 Shields.", chainFrom: ["archery-range"], chainTo: [], playerCount: 3 },
        // ---- Age III extra content (5-7 players) ----
        { id: "marble-quarry", name: "Marble Quarry", emoji: "🏛️", age: 3, type: "civilian",
            cost: { stone: 2, clay: 1 }, produces: [], producesChoice: false, vp: 6, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Worth 6 VP.", chainFrom: [], chainTo: [], playerCount: 5 },
        { id: "glass-blowers", name: "Glass Blowers", emoji: "🔷", age: 3, type: "commercial",
            cost: {}, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 8,
            science: null, effect: "Gives 8 coins when built.", chainFrom: [], chainTo: [], playerCount: 5 },
        { id: "engineers-workshop", name: "Engineers' Workshop", emoji: "⚙️", age: 3, type: "scientific",
            cost: { loom: 2, ore: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: "gear", effect: "Grants a Gear science symbol.", chainFrom: [], chainTo: [], playerCount: 5 },
        { id: "grand-plaza", name: "Grand Plaza", emoji: "🏞️", age: 3, type: "civilian",
            cost: { clay: 2, wood: 2 }, produces: [], producesChoice: false, vp: 7, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Worth 7 VP.", chainFrom: [], chainTo: [], playerCount: 5 },
        { id: "market-row", name: "Market Row", emoji: "🏢", age: 3, type: "commercial",
            cost: {}, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 6,
            science: null, effect: "Gives 6 coins when built.", chainFrom: [], chainTo: [], playerCount: 5 },
        { id: "bastion", name: "Bastion", emoji: "🏯", age: 3, type: "military",
            cost: { stone: 2, ore: 1 }, produces: [], producesChoice: false, vp: 0, shields: 3, coinsOnPlay: 0,
            science: null, effect: "Grants 3 Shields.", chainFrom: [], chainTo: [], playerCount: 5 },
        { id: "temple-gardens", name: "Temple Gardens", emoji: "🕍", age: 3, type: "civilian",
            cost: { glass: 1, loom: 1, papyrus: 1 }, produces: [], producesChoice: false, vp: 7, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Worth 7 VP.", chainFrom: [], chainTo: [], playerCount: 6 },
        { id: "silk-workshops", name: "Silk Workshops", emoji: "🧵", age: 3, type: "commercial",
            cost: {}, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 8,
            science: null, effect: "Gives 8 coins when built.", chainFrom: [], chainTo: [], playerCount: 6 },
        { id: "metal-foundry", name: "Metal Foundry", emoji: "⛏️", age: 3, type: "military",
            cost: { stone: 2, ore: 1 }, produces: [], producesChoice: false, vp: 0, shields: 3, coinsOnPlay: 0,
            science: null, effect: "Grants 3 Shields.", chainFrom: [], chainTo: [], playerCount: 6 },
        { id: "regal-court", name: "Regal Court", emoji: "🏰", age: 3, type: "civilian",
            cost: { stone: 2, ore: 1, glass: 1 }, produces: [], producesChoice: false, vp: 8, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Worth 8 VP.", chainFrom: [], chainTo: [], playerCount: 6 },
        { id: "counting-house", name: "Counting House", emoji: "⚓", age: 3, type: "commercial",
            cost: {}, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 6,
            science: null, effect: "Gives 6 coins when built.", chainFrom: [], chainTo: [], playerCount: 6 },
        { id: "grand-academy", name: "Grand Academy", emoji: "📚", age: 3, type: "scientific",
            cost: { papyrus: 2, loom: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: "tablet", effect: "Grants a Tablet science symbol.", chainFrom: [], chainTo: [], playerCount: 6 },
        { id: "military-academy", name: "Military Academy", emoji: "🎖️", age: 3, type: "military",
            cost: { wood: 2, ore: 1 }, produces: [], producesChoice: false, vp: 0, shields: 3, coinsOnPlay: 0,
            science: null, effect: "Grants 3 Shields.", chainFrom: [], chainTo: [], playerCount: 7 },
        { id: "merchant-house", name: "Merchant House", emoji: "🧳", age: 3, type: "commercial",
            cost: {}, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 8,
            science: null, effect: "Gives 8 coins when built.", chainFrom: [], chainTo: [], playerCount: 7 },
        { id: "harbor-tower", name: "Harbor Tower", emoji: "🚨", age: 3, type: "commercial",
            cost: {}, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 6,
            science: null, effect: "Gives 6 coins when built.", chainFrom: [], chainTo: [], playerCount: 7 },
        { id: "monumental-arch", name: "Monumental Arch", emoji: "🗼", age: 3, type: "civilian",
            cost: { clay: 2, stone: 1 }, produces: [], producesChoice: false, vp: 6, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Worth 6 VP.", chainFrom: [], chainTo: [], playerCount: 7 },
        { id: "hall-of-scholars", name: "Hall of Scholars", emoji: "📖", age: 3, type: "civilian",
            cost: { stone: 1, loom: 1, papyrus: 1 }, produces: [], producesChoice: false, vp: 6, shields: 0, coinsOnPlay: 0,
            science: null, effect: "Worth 6 VP.", chainFrom: [], chainTo: [], playerCount: 7 },
        { id: "chart-house", name: "Chart House", emoji: "⚙️", age: 3, type: "scientific",
            cost: { loom: 2, clay: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            science: "gear", effect: "Grants a Gear science symbol.", chainFrom: [], chainTo: [], playerCount: 7 },
        // ---- Guilds (Age III, Purple) — scoring rules transcribed from docs/rules.md ----
        { id: "spies-guild", name: "Spies Guild", emoji: "🕵️", age: 3, type: "guild",
            cost: { clay: 2, glass: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0,
            coinsOnPlay: 0, science: null, effect: "1 VP for each Military card present in both neighbouring cities.",
            chainFrom: [], chainTo: [], guildRule: { kind: "countCardType", cardType: "military", scope: "neighbors", per: 1 }, playerCount: 3 },
        { id: "magistrates-guild", name: "Magistrates Guild", emoji: "⚖️", age: 3, type: "guild",
            cost: { stone: 2, wood: 1, loom: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0,
            coinsOnPlay: 0, science: null, effect: "1 VP for each Civilian card present in both neighbouring cities.",
            chainFrom: [], chainTo: [], guildRule: { kind: "countCardType", cardType: "civilian", scope: "neighbors", per: 1 }, playerCount: 3 },
        { id: "workers-guild", name: "Workers Guild", emoji: "👷", age: 3, type: "guild",
            cost: { ore: 2, clay: 1, stone: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0,
            coinsOnPlay: 0, science: null, effect: "1 VP for each Raw Material card present in both neighbouring cities.",
            chainFrom: [], chainTo: [], guildRule: { kind: "countCardType", cardType: "basic", scope: "neighbors", per: 1 }, playerCount: 3 },
        { id: "craftsmens-guild", name: "Craftsmens Guild", emoji: "🛠️", age: 3, type: "guild",
            cost: { ore: 2, stone: 2 }, produces: [], producesChoice: false, vp: 0, shields: 0,
            coinsOnPlay: 0, science: null, effect: "2 VP for each Manufactured Good card present in both neighbouring cities.",
            chainFrom: [], chainTo: [], guildRule: { kind: "countCardType", cardType: "manufactured", scope: "neighbors", per: 2 }, playerCount: 3 },
        { id: "traders-guild", name: "Traders Guild", emoji: "🧳", age: 3, type: "guild",
            cost: { loom: 1, papyrus: 1, glass: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0,
            coinsOnPlay: 0, science: null, effect: "1 VP for each Commercial card present in both neighbouring cities.",
            chainFrom: [], chainTo: [], guildRule: { kind: "countCardType", cardType: "commercial", scope: "neighbors", per: 1 }, playerCount: 3 },
        { id: "philosophers-guild", name: "Philosophers Guild", emoji: "📖", age: 3, type: "guild",
            cost: { clay: 3, loom: 1, papyrus: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0,
            coinsOnPlay: 0, science: null, effect: "1 VP for each Scientific card present in both neighbouring cities.",
            chainFrom: [], chainTo: [], guildRule: { kind: "countCardType", cardType: "scientific", scope: "neighbors", per: 1 }, playerCount: 3 },
        { id: "builders-guild", name: "Builders Guild", emoji: "🏗️", age: 3, type: "guild",
            cost: { stone: 2, clay: 2, glass: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0,
            coinsOnPlay: 0, science: null, effect: "1 VP for each Wonder stage built in the neighbouring cities and in your own city.",
            chainFrom: [], chainTo: [], guildRule: { kind: "countWonderStages", scope: "neighborsAndSelf", per: 1 }, playerCount: 3 },
        { id: "shipowners-guild", name: "Shipowners Guild", emoji: "🚢", age: 3, type: "guild",
            cost: { wood: 3, papyrus: 1, glass: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0,
            coinsOnPlay: 0, science: null, effect: "1 VP for each Raw Material, Manufactured Good, and Guild card in your city.",
            chainFrom: [], chainTo: [], guildRule: { kind: "countCardTypes", cardTypes: ["basic", "manufactured", "guild"], scope: "self", per: 1 }, playerCount: 3 },
        { id: "strategists-guild", name: "Strategists Guild", emoji: "🎖️", age: 3, type: "guild",
            cost: { ore: 2, stone: 1, loom: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0,
            coinsOnPlay: 0, science: null, effect: "1 VP for each defeat token present in the neighbouring cities.",
            chainFrom: [], chainTo: [], guildRule: { kind: "countDefeatTokens", scope: "neighbors", per: 1 }, playerCount: 3 },
        { id: "scientists-guild", name: "Scientists Guild", emoji: "🔬", age: 3, type: "guild",
            cost: { wood: 2, ore: 2, papyrus: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0,
            coinsOnPlay: 0, science: null, effect: "Gain an extra scientific symbol of your choice.",
            chainFrom: [], chainTo: [], special: "extraScienceSymbol", playerCount: 3 },
    ],
};
if (typeof module !== "undefined" && module.exports)
    module.exports = GameData;
