// 7 Wonders — static game data (card types, resources, cards, Wonder boards). Loaded before
// script.js. This is the file admin/index.html edits and re-exports — keep all content data
// here, keep logic in script.js. See docs/requirements.md §3/§3b for the data shapes.
"use strict";

const GameData = {
  CARD_TYPES: {
    raw:          { label: "Raw Material",       color: "#c98a4b", colorDim: "#5a4230" },
    manufactured: { label: "Manufactured Good",   color: "#b9bec7", colorDim: "#454a52" },
    civilian:     { label: "Civilian Structure",  color: "#5b9bd5", colorDim: "#22384a" },
    scientific:   { label: "Scientific Structure",color: "#7ec98f", colorDim: "#22402c" },
    commercial:   { label: "Commercial Structure",color: "#f0c674", colorDim: "#4a3d1e" },
    military:     { label: "Military Structure",  color: "#e0555e", colorDim: "#4a2226" },
    guild:        { label: "Guild",               color: "#b489d6", colorDim: "#3a2a49" },
  },

  RESOURCES: {
    wood:    { label: "Wood",    emoji: "🪵" },
    clay:    { label: "Clay",    emoji: "🧱" },
    ore:     { label: "Ore",     emoji: "⛏️" },
    stone:   { label: "Stone",   emoji: "🪨" },
    glass:   { label: "Glass",   emoji: "🔷" },
    loom:    { label: "Loom",    emoji: "🧵" },
    papyrus: { label: "Papyrus", emoji: "📜" },
  },

  SCIENCE_SYMBOLS: {
    tablet:  { label: "Tablet",  emoji: "📚" },
    compass: { label: "Compass", emoji: "🧭" },
    gear:    { label: "Gear",    emoji: "⚙️" },
  },

  // Illustration art for card faces (game/images/). Only 3 images exist for 88 cards, so there's
  // no realistic per-type dedication (that would make e.g. every civilian card — nearly a third
  // of the deck — show the exact same photo). Instead script.js's cardArtUrl() hashes each
  // card's own id into this one shared pool, deterministically (same card always shows the same
  // art) but spread evenly across all types for more variety within any given hand.
  CARD_ART: {
    pool: ["images/civ-baths.jpg", "images/comm-tavern-b.jpg", "images/sci-workshop-b.jpg"],
  },

  // Base game only — the Leaders expansion and the 2-player "Free City" variant (see
  // docs/rules.md) are not implemented. Content below is sized for 3-4 players; the same fixed
  // pool is reused regardless of player count (a documented simplification — the physical game
  // varies deck composition by player count, e.g. more copies of basic resource cards at higher
  // counts; this implementation does not).
  SUPPORTED_PLAYER_COUNTS: [3, 4],

  // Seven Wonder boards. Each has a starting resource (produced for free from turn 1) and 3
  // stages, each with a resource cost and an effect. `effect.power` names one of 4 special
  // abilities (see docs/rules.md "Wonder board powers"); the rules summary sheet doesn't tie
  // these to specific named boards, so this assignment (one board per power) is this
  // implementation's own placeholder choice, not verified against the physical boards. Stage
  // costs/effects are a reasonable original design sized for this card pool's economy, not
  // transcribed from the physical game — see the content-status note on CARDS below.
  WONDERS: [
    {
      id: "gizah", name: "Gizah", emoji: "🔺", resource: "stone",
      stages: [
        { cost: { wood: 2 }, effect: { vp: 3 } },
        { cost: { stone: 2 }, effect: { vp: 5 } },
        { cost: { clay: 2, ore: 1 }, effect: { vp: 7 } },
      ],
    },
    {
      id: "rhodos", name: "Rhodos", emoji: "🗿", resource: "ore",
      stages: [
        { cost: { wood: 2 }, effect: { coins: 3, shields: 1 } },
        { cost: { clay: 2 }, effect: { shields: 1, vp: 3 } },
        { cost: { ore: 3 }, effect: { vp: 7 } },
      ],
    },
    {
      id: "ephesos", name: "Ephesos", emoji: "🛕", resource: "papyrus",
      stages: [
        { cost: { stone: 2 }, effect: { coins: 4 } },
        { cost: { wood: 2 }, effect: { coins: 4, vp: 2 } },
        { cost: { papyrus: 2 }, effect: { vp: 7 } },
      ],
    },
    {
      id: "babylon", name: "Babylon", emoji: "🌳", resource: "clay",
      stages: [
        { cost: { clay: 2 }, effect: { vp: 3 } },
        { cost: { wood: 2 }, effect: { vp: 4 } },
        { cost: { ore: 2, papyrus: 1 }, effect: { vp: 4, power: "copyNeighborGuild" } },
      ],
    },
    {
      id: "olympia", name: "Olympia", emoji: "🏟️", resource: "wood",
      stages: [
        { cost: { wood: 2 }, effect: { vp: 3 } },
        { cost: { stone: 2 }, effect: { vp: 2, power: "freeBuildPerAge" } },
        { cost: { ore: 2, loom: 1 }, effect: { vp: 7 } },
      ],
    },
    {
      id: "halikarnassos", name: "Halikarnassos", emoji: "⚰️", resource: "loom",
      stages: [
        { cost: { clay: 2 }, effect: { coins: 4 } },
        { cost: { ore: 2 }, effect: { vp: 2, power: "discardPileBuild" } },
        { cost: { stone: 2, glass: 1 }, effect: { vp: 7 } },
      ],
    },
    {
      id: "alexandria", name: "Alexandria", emoji: "🗼", resource: "glass",
      stages: [
        { cost: { stone: 2 }, effect: { vp: 3 } },
        { cost: { ore: 2 }, effect: { vp: 2, power: "lastCardAlternative" } },
        { cost: { wood: 2, papyrus: 1 }, effect: { vp: 7 } },
      ],
    },
  ],

  // Card pool — sample content, sized to deal 3 Ages x 7 cards x up to 4 players (28 per Age;
  // Age III = 22 non-Guild + 6 of 10 Guilds kept, per docs/rules.md's "players + 2" rule). This
  // is NOT the authoritative ~90-card physical deck (exact per-card costs/effects and
  // player-count-scaled counts are box-sourced and not transcribed) — names, costs and VP values
  // here are an original placeholder design good enough to play the real rules against. Guild
  // scoring rules, the Age II/III commerce-card mechanics, and the science-scoring formula *are*
  // transcribed from docs/rules.md and should be accurate. Replace/expand via admin/index.html
  // once real content is authored.
  CARDS: [
    // ---- Age I ----
    { id: "lumber-yard", name: "Lumber Yard", emoji: "🪵", age: 1, type: "raw",
      cost: {}, produces: ["wood"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
      science: null, effect: "Produces 1 Wood.", chainFrom: [], chainTo: [] },
    { id: "forest-cave", name: "Forest Cave", emoji: "🌲", age: 1, type: "raw",
      cost: {}, produces: ["wood"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
      science: null, effect: "Produces 1 Wood.", chainFrom: [], chainTo: [] },
    { id: "ore-vein", name: "Ore Vein", emoji: "⛏️", age: 1, type: "raw",
      cost: {}, produces: ["ore"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
      science: null, effect: "Produces 1 Ore.", chainFrom: [], chainTo: [] },
    { id: "mine", name: "Mine", emoji: "⛰️", age: 1, type: "raw",
      cost: {}, produces: ["ore"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
      science: null, effect: "Produces 1 Ore.", chainFrom: [], chainTo: [] },
    { id: "clay-pool", name: "Clay Pool", emoji: "🧱", age: 1, type: "raw",
      cost: {}, produces: ["clay"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
      science: null, effect: "Produces 1 Clay.", chainFrom: [], chainTo: [] },
    { id: "clay-pit", name: "Clay Pit", emoji: "🧱", age: 1, type: "raw",
      cost: {}, produces: ["clay"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
      science: null, effect: "Produces 1 Clay.", chainFrom: [], chainTo: [] },
    { id: "stone-pit", name: "Stone Pit", emoji: "🪨", age: 1, type: "raw",
      cost: {}, produces: ["stone"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
      science: null, effect: "Produces 1 Stone.", chainFrom: [], chainTo: [] },
    { id: "quarry", name: "Quarry", emoji: "🪨", age: 1, type: "raw",
      cost: {}, produces: ["stone"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
      science: null, effect: "Produces 1 Stone.", chainFrom: [], chainTo: [] },

    { id: "glassworks", name: "Glassworks", emoji: "🔷", age: 1, type: "manufactured",
      cost: {}, produces: ["glass"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
      science: null, effect: "Produces 1 Glass.", chainFrom: [], chainTo: ["stained-glass-works"] },
    { id: "press", name: "Press", emoji: "📜", age: 1, type: "manufactured",
      cost: {}, produces: ["papyrus"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
      science: null, effect: "Produces 1 Papyrus.", chainFrom: [], chainTo: [] },
    { id: "loom-house", name: "Loom House", emoji: "🧵", age: 1, type: "manufactured",
      cost: {}, produces: ["loom"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
      science: null, effect: "Produces 1 Loom.", chainFrom: [], chainTo: [] },

    { id: "baths", name: "Baths", emoji: "🛁", age: 1, type: "civilian",
      cost: { stone: 1 }, produces: [], producesChoice: false, vp: 3, shields: 0, coinsOnPlay: 0,
      science: null, effect: "Worth 3 VP.", chainFrom: [], chainTo: ["aqueduct"] },
    { id: "altar", name: "Altar", emoji: "⛩️", age: 1, type: "civilian",
      cost: {}, produces: [], producesChoice: false, vp: 2, shields: 0, coinsOnPlay: 0,
      science: null, effect: "Worth 2 VP.", chainFrom: [], chainTo: [] },
    { id: "theater", name: "Theater", emoji: "🎭", age: 1, type: "civilian",
      cost: {}, produces: [], producesChoice: false, vp: 2, shields: 0, coinsOnPlay: 0,
      science: null, effect: "Worth 2 VP.", chainFrom: [], chainTo: [] },
    { id: "well", name: "Well", emoji: "⛲", age: 1, type: "civilian",
      cost: { wood: 1 }, produces: [], producesChoice: false, vp: 3, shields: 0, coinsOnPlay: 0,
      science: null, effect: "Worth 3 VP.", chainFrom: [], chainTo: [] },
    { id: "shrine", name: "Shrine", emoji: "⛪", age: 1, type: "civilian",
      cost: {}, produces: [], producesChoice: false, vp: 2, shields: 0, coinsOnPlay: 0,
      science: null, effect: "Worth 2 VP.", chainFrom: [], chainTo: ["temple"] },
    { id: "statue-garden", name: "Statue Garden", emoji: "🌷", age: 1, type: "civilian",
      cost: { clay: 1 }, produces: [], producesChoice: false, vp: 3, shields: 0, coinsOnPlay: 0,
      science: null, effect: "Worth 3 VP.", chainFrom: [], chainTo: [] },
    { id: "plaza", name: "Plaza", emoji: "🏙️", age: 1, type: "civilian",
      cost: { ore: 1 }, produces: [], producesChoice: false, vp: 3, shields: 0, coinsOnPlay: 0,
      science: null, effect: "Worth 3 VP.", chainFrom: [], chainTo: [] },

    { id: "scriptorium", name: "Scriptorium", emoji: "📚", age: 1, type: "scientific",
      cost: { papyrus: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
      science: "tablet", effect: "Grants a Tablet science symbol.", chainFrom: [], chainTo: ["courthouse"] },
    { id: "workshop", name: "Workshop", emoji: "🧭", age: 1, type: "scientific",
      cost: { glass: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
      science: "compass", effect: "Grants a Compass science symbol.", chainFrom: [], chainTo: [] },
    { id: "apothecary", name: "Apothecary", emoji: "⚙️", age: 1, type: "scientific",
      cost: { loom: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
      science: "gear", effect: "Grants a Gear science symbol.", chainFrom: [], chainTo: [] },

    { id: "tavern", name: "Tavern", emoji: "🍺", age: 1, type: "commercial",
      cost: {}, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 5,
      science: null, effect: "Gives 5 coins when built.", chainFrom: [], chainTo: [] },
    { id: "market", name: "Market", emoji: "🛒", age: 1, type: "commercial",
      cost: {}, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 3,
      science: null, effect: "Gives 3 coins when built.", chainFrom: [], chainTo: [] },
    { id: "trading-post", name: "Trading Post", emoji: "🤝", age: 1, type: "commercial",
      cost: {}, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 3,
      science: null, effect: "Gives 3 coins when built. Buy raw materials from either neighbour for 1 coin instead of 2.",
      chainFrom: [], chainTo: [], tradeDiscount: { category: "raw" } },
    { id: "caravanserai", name: "Caravanserai", emoji: "🐫", age: 1, type: "commercial",
      cost: {}, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 3,
      science: null, effect: "Gives 3 coins when built. Buy manufactured goods from either neighbour for 1 coin instead of 2.",
      chainFrom: [], chainTo: [], tradeDiscount: { category: "manufactured" } },

    { id: "stockade", name: "Stockade", emoji: "🛡️", age: 1, type: "military",
      cost: { wood: 1 }, produces: [], producesChoice: false, vp: 0, shields: 1, coinsOnPlay: 0,
      science: null, effect: "Grants 1 Shield.", chainFrom: [], chainTo: ["walls"] },
    { id: "garrison", name: "Garrison", emoji: "🗡️", age: 1, type: "military",
      cost: { ore: 1 }, produces: [], producesChoice: false, vp: 0, shields: 1, coinsOnPlay: 0,
      science: null, effect: "Grants 1 Shield.", chainFrom: [], chainTo: [] },
    { id: "barracks", name: "Barracks", emoji: "⚔️", age: 1, type: "military",
      cost: { clay: 1 }, produces: [], producesChoice: false, vp: 0, shields: 1, coinsOnPlay: 0,
      science: null, effect: "Grants 1 Shield.", chainFrom: [], chainTo: ["archery-range"] },

    // ---- Age II ----
    { id: "sawmill", name: "Sawmill", emoji: "🪚", age: 2, type: "raw",
      cost: {}, produces: ["wood"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
      science: null, effect: "Produces 2 Wood.", produceCount: 2, chainFrom: [], chainTo: [] },
    { id: "foundry", name: "Foundry", emoji: "⛏️", age: 2, type: "raw",
      cost: {}, produces: ["ore"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
      science: null, effect: "Produces 2 Ore.", produceCount: 2, chainFrom: [], chainTo: [] },
    { id: "brickyard", name: "Brickyard", emoji: "🧱", age: 2, type: "raw",
      cost: {}, produces: ["clay"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
      science: null, effect: "Produces 2 Clay.", produceCount: 2, chainFrom: [], chainTo: [] },
    { id: "shelf-quarry", name: "Shelf Quarry", emoji: "🪨", age: 2, type: "raw",
      cost: {}, produces: ["stone"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
      science: null, effect: "Produces 2 Stone.", produceCount: 2, chainFrom: [], chainTo: [] },

    { id: "stained-glass-works", name: "Stained Glass Works", emoji: "🔷", age: 2, type: "manufactured",
      cost: {}, produces: ["glass"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
      science: null, effect: "Produces 1 Glass.", chainFrom: ["glassworks"], chainTo: [] },
    { id: "papyrus-mill", name: "Papyrus Mill", emoji: "📜", age: 2, type: "manufactured",
      cost: {}, produces: ["papyrus"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
      science: null, effect: "Produces 1 Papyrus.", chainFrom: [], chainTo: [] },
    { id: "loom-shed", name: "Loom Shed", emoji: "🧵", age: 2, type: "manufactured",
      cost: {}, produces: ["loom"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
      science: null, effect: "Produces 1 Loom.", chainFrom: [], chainTo: [] },

    { id: "caravan", name: "Caravan", emoji: "🚚", age: 2, type: "raw",
      cost: {}, produces: ["clay", "ore", "stone", "wood"], producesChoice: true, vp: 0, shields: 0,
      coinsOnPlay: 0, science: null, effect: "Produces 1 of your choice: Clay, Ore, Stone, or Wood.",
      chainFrom: [], chainTo: [] },
    { id: "bazaar", name: "Bazaar", emoji: "🏺", age: 2, type: "manufactured",
      cost: {}, produces: ["glass", "loom", "papyrus"], producesChoice: true, vp: 0, shields: 0,
      coinsOnPlay: 0, science: null, effect: "Produces 1 of your choice: Glass, Loom, or Papyrus.",
      chainFrom: [], chainTo: [] },

    { id: "aqueduct", name: "Aqueduct", emoji: "🌉", age: 2, type: "civilian",
      cost: { stone: 2 }, produces: [], producesChoice: false, vp: 5, shields: 0, coinsOnPlay: 0,
      science: null, effect: "Worth 5 VP.", chainFrom: ["baths"], chainTo: [] },
    { id: "temple", name: "Temple", emoji: "🏯", age: 2, type: "civilian",
      cost: { wood: 1, clay: 1 }, produces: [], producesChoice: false, vp: 4, shields: 0, coinsOnPlay: 0,
      science: null, effect: "Worth 4 VP.", chainFrom: ["shrine"], chainTo: ["grand-temple"] },
    { id: "statue", name: "Statue", emoji: "🗽", age: 2, type: "civilian",
      cost: { ore: 2 }, produces: [], producesChoice: false, vp: 4, shields: 0, coinsOnPlay: 0,
      science: null, effect: "Worth 4 VP.", chainFrom: [], chainTo: [] },
    { id: "courtyard", name: "Courtyard", emoji: "🏘️", age: 2, type: "civilian",
      cost: { clay: 2 }, produces: [], producesChoice: false, vp: 4, shields: 0, coinsOnPlay: 0,
      science: null, effect: "Worth 4 VP.", chainFrom: [], chainTo: [] },
    { id: "gardens", name: "Gardens", emoji: "🌺", age: 2, type: "civilian",
      cost: { clay: 2 }, produces: [], producesChoice: false, vp: 5, shields: 0, coinsOnPlay: 0,
      science: null, effect: "Worth 5 VP.", chainFrom: [], chainTo: [] },
    { id: "senate", name: "Senate", emoji: "🏛️", age: 2, type: "civilian",
      cost: { wood: 1, stone: 1, ore: 1 }, produces: [], producesChoice: false, vp: 6, shields: 0,
      coinsOnPlay: 0, science: null, effect: "Worth 6 VP.", chainFrom: [], chainTo: [] },
    { id: "forum-hall", name: "Forum Hall", emoji: "🏢", age: 2, type: "civilian",
      cost: { clay: 2 }, produces: [], producesChoice: false, vp: 4, shields: 0, coinsOnPlay: 0,
      science: null, effect: "Worth 4 VP.", chainFrom: [], chainTo: [] },
    { id: "amphitheater", name: "Amphitheater", emoji: "🎪", age: 2, type: "civilian",
      cost: { stone: 2 }, produces: [], producesChoice: false, vp: 5, shields: 0, coinsOnPlay: 0,
      science: null, effect: "Worth 5 VP.", chainFrom: [], chainTo: [] },

    { id: "courthouse", name: "Courthouse", emoji: "📚", age: 2, type: "scientific",
      cost: { loom: 2 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
      science: "tablet", effect: "Grants a Tablet science symbol.", chainFrom: ["scriptorium"], chainTo: ["university-of-science"] },
    { id: "observatory", name: "Observatory", emoji: "🧭", age: 2, type: "scientific",
      cost: { ore: 2 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
      science: "compass", effect: "Grants a Compass science symbol.", chainFrom: [], chainTo: ["observatory-tower"] },
    { id: "pharmacy", name: "Pharmacy", emoji: "⚙️", age: 2, type: "scientific",
      cost: { papyrus: 2 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
      science: "gear", effect: "Grants a Gear science symbol.", chainFrom: [], chainTo: ["lodge"] },

    { id: "customs-house", name: "Customs House", emoji: "🏦", age: 2, type: "commercial",
      cost: {}, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 6,
      science: null, effect: "Gives 6 coins when built.", chainFrom: [], chainTo: [] },
    { id: "forum-market", name: "Forum Market", emoji: "💰", age: 2, type: "commercial",
      cost: {}, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
      science: null, effect: "Worth 1 coin per Raw Material card built in your city and in the 2 neighbouring cities.",
      chainFrom: [], chainTo: [], coinsPerCardType: { cardType: "raw", per: 1, scope: "selfAndNeighbors" } },
    { id: "guild-exchange", name: "Guild Exchange", emoji: "💱", age: 2, type: "commercial",
      cost: {}, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
      science: null, effect: "Worth 2 coins per Manufactured Good card built in your city and in the 2 neighbouring cities.",
      chainFrom: [], chainTo: [], coinsPerCardType: { cardType: "manufactured", per: 2, scope: "selfAndNeighbors" } },
    { id: "dockyard", name: "Dockyard", emoji: "⚓", age: 2, type: "commercial",
      cost: {}, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 6,
      science: null, effect: "Gives 6 coins when built.", chainFrom: [], chainTo: [] },
    { id: "bank", name: "Bank", emoji: "🏦", age: 2, type: "commercial",
      cost: {}, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 8,
      science: null, effect: "Gives 8 coins when built.", chainFrom: [], chainTo: [] },

    { id: "walls", name: "Walls", emoji: "🧱", age: 2, type: "military",
      cost: { stone: 2 }, produces: [], producesChoice: false, vp: 0, shields: 2, coinsOnPlay: 0,
      science: null, effect: "Grants 2 Shields.", chainFrom: ["stockade"], chainTo: ["siege-camp"] },
    { id: "archery-range", name: "Archery Range", emoji: "🏹", age: 2, type: "military",
      cost: { wood: 2 }, produces: [], producesChoice: false, vp: 0, shields: 2, coinsOnPlay: 0,
      science: null, effect: "Grants 2 Shields.", chainFrom: ["barracks"], chainTo: ["citadel"] },
    { id: "training-ground", name: "Training Ground", emoji: "🎯", age: 2, type: "military",
      cost: { ore: 1, wood: 1 }, produces: [], producesChoice: false, vp: 0, shields: 2, coinsOnPlay: 0,
      science: null, effect: "Grants 2 Shields.", chainFrom: [], chainTo: [] },

    // ---- Age III (non-Guild) ----
    { id: "pantheon", name: "Pantheon", emoji: "⛩️", age: 3, type: "civilian",
      cost: { clay: 2, loom: 1, papyrus: 1 }, produces: [], producesChoice: false, vp: 8, shields: 0,
      coinsOnPlay: 0, science: null, effect: "Worth 8 VP.", chainFrom: [], chainTo: [] },
    { id: "gardens-palace", name: "Gardens Palace", emoji: "🏞️", age: 3, type: "civilian",
      cost: { clay: 2, wood: 2 }, produces: [], producesChoice: false, vp: 7, shields: 0,
      coinsOnPlay: 0, science: null, effect: "Worth 7 VP.", chainFrom: [], chainTo: [] },
    { id: "town-hall", name: "Town Hall", emoji: "🏤", age: 3, type: "civilian",
      cost: { stone: 3, glass: 1 }, produces: [], producesChoice: false, vp: 7, shields: 0,
      coinsOnPlay: 0, science: null, effect: "Worth 7 VP.", chainFrom: [], chainTo: [] },
    { id: "palace", name: "Palace", emoji: "🏰", age: 3, type: "civilian",
      cost: { stone: 2, ore: 1, glass: 1 }, produces: [], producesChoice: false, vp: 8, shields: 0,
      coinsOnPlay: 0, science: null, effect: "Worth 8 VP.", chainFrom: [], chainTo: [] },
    { id: "obelisk", name: "Obelisk", emoji: "🗿", age: 3, type: "civilian",
      cost: { stone: 2, wood: 1 }, produces: [], producesChoice: false, vp: 6, shields: 0,
      coinsOnPlay: 0, science: null, effect: "Worth 6 VP.", chainFrom: [], chainTo: [] },
    { id: "senate-hall", name: "Senate Hall", emoji: "🏛️", age: 3, type: "civilian",
      cost: { ore: 2, loom: 1 }, produces: [], producesChoice: false, vp: 6, shields: 0,
      coinsOnPlay: 0, science: null, effect: "Worth 6 VP.", chainFrom: [], chainTo: [] },
    { id: "grand-arena", name: "Grand Arena", emoji: "🏟️", age: 3, type: "civilian",
      cost: { stone: 3 }, produces: [], producesChoice: false, vp: 6, shields: 0,
      coinsOnPlay: 0, science: null, effect: "Worth 6 VP.", chainFrom: [], chainTo: [] },
    { id: "university", name: "University", emoji: "🎓", age: 3, type: "civilian",
      cost: { wood: 2, papyrus: 1 }, produces: [], producesChoice: false, vp: 5, shields: 0,
      coinsOnPlay: 0, science: null, effect: "Worth 5 VP.", chainFrom: [], chainTo: [] },
    { id: "library", name: "Library", emoji: "📖", age: 3, type: "civilian",
      cost: { stone: 1, loom: 1, papyrus: 1 }, produces: [], producesChoice: false, vp: 6, shields: 0,
      coinsOnPlay: 0, science: null, effect: "Worth 6 VP.", chainFrom: [], chainTo: [] },
    { id: "monument", name: "Monument", emoji: "🗼", age: 3, type: "civilian",
      cost: { clay: 2, stone: 1 }, produces: [], producesChoice: false, vp: 6, shields: 0,
      coinsOnPlay: 0, science: null, effect: "Worth 6 VP.", chainFrom: [], chainTo: [] },
    { id: "sanctuary", name: "Sanctuary", emoji: "🕍", age: 3, type: "civilian",
      cost: { glass: 1, loom: 1, papyrus: 1 }, produces: [], producesChoice: false, vp: 7, shields: 0,
      coinsOnPlay: 0, science: null, effect: "Worth 7 VP.", chainFrom: [], chainTo: [] },
    { id: "grand-temple", name: "Grand Temple", emoji: "🏯", age: 3, type: "civilian",
      cost: { clay: 1, glass: 1, loom: 1 }, produces: [], producesChoice: false, vp: 7, shields: 0,
      coinsOnPlay: 0, science: null, effect: "Worth 7 VP.", chainFrom: ["temple"], chainTo: [] },

    { id: "university-of-science", name: "University of Science", emoji: "📚", age: 3, type: "scientific",
      cost: { papyrus: 2, loom: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0,
      coinsOnPlay: 0, science: "tablet", effect: "Grants a Tablet science symbol.",
      chainFrom: ["courthouse"], chainTo: [] },
    { id: "observatory-tower", name: "Observatory Tower", emoji: "🧭", age: 3, type: "scientific",
      cost: { ore: 2, glass: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0,
      coinsOnPlay: 0, science: "compass", effect: "Grants a Compass science symbol.",
      chainFrom: ["observatory"], chainTo: [] },
    { id: "lodge", name: "Lodge", emoji: "⚙️", age: 3, type: "scientific",
      cost: { loom: 2, clay: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0,
      coinsOnPlay: 0, science: "gear", effect: "Grants a Gear science symbol.",
      chainFrom: ["pharmacy"], chainTo: [] },

    { id: "arsenal", name: "Arsenal", emoji: "🏹", age: 3, type: "commercial",
      cost: {}, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0, science: null,
      effect: "Gives 3 coins per Wonder stage built in its home city when played. At game end, worth 1 VP per Wonder stage built in its home city.",
      chainFrom: [], chainTo: [],
      coinsPerWonderStage: { per: 3, scope: "self" }, vpPerWonderStage: { per: 1, scope: "self" } },
    { id: "lighthouse", name: "Lighthouse", emoji: "🚨", age: 3, type: "commercial",
      cost: {}, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0, science: null,
      effect: "Gives 1 coin per Raw Material card in your city when played. At game end, worth 1 VP for each Raw Material card present in your city.",
      chainFrom: [], chainTo: [],
      coinsPerCardType: { cardType: "raw", per: 1, scope: "self" }, vpPerCardType: { cardType: "raw", per: 1, scope: "self" } },
    { id: "haven", name: "Haven", emoji: "⚓", age: 3, type: "commercial",
      cost: {}, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0, science: null,
      effect: "Gives 2 coins per Manufactured Good card in your city when played. At game end, worth 2 VP for each Manufactured Good card present in your city.",
      chainFrom: [], chainTo: [],
      coinsPerCardType: { cardType: "manufactured", per: 2, scope: "self" }, vpPerCardType: { cardType: "manufactured", per: 2, scope: "self" } },
    { id: "chamber-of-commerce", name: "Chamber of Commerce", emoji: "🏢", age: 3, type: "commercial",
      cost: {}, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0, science: null,
      effect: "Gives 1 coin per Commercial card in your city (including itself) when played. At game end, worth 1 VP for each Commercial card present in your city.",
      chainFrom: [], chainTo: [],
      coinsPerCardType: { cardType: "commercial", per: 1, scope: "self", includeSelf: true },
      vpPerCardType: { cardType: "commercial", per: 1, scope: "self", includeSelf: true } },

    { id: "fortress", name: "Fortress", emoji: "🏯", age: 3, type: "military",
      cost: { stone: 2, ore: 1 }, produces: [], producesChoice: false, vp: 0, shields: 3, coinsOnPlay: 0,
      science: null, effect: "Grants 3 Shields.", chainFrom: [], chainTo: [] },
    { id: "siege-camp", name: "Siege Camp", emoji: "🏕️", age: 3, type: "military",
      cost: { wood: 2, ore: 1 }, produces: [], producesChoice: false, vp: 0, shields: 3, coinsOnPlay: 0,
      science: null, effect: "Grants 3 Shields.", chainFrom: ["walls"], chainTo: [] },
    { id: "citadel", name: "Citadel", emoji: "🏰", age: 3, type: "military",
      cost: { stone: 3 }, produces: [], producesChoice: false, vp: 0, shields: 3, coinsOnPlay: 0,
      science: null, effect: "Grants 3 Shields.", chainFrom: ["archery-range"], chainTo: [] },

    // ---- Guilds (Age III, Purple) — scoring rules transcribed from docs/rules.md ----
    { id: "spies-guild", name: "Spies Guild", emoji: "🕵️", age: 3, type: "guild",
      cost: { clay: 2, glass: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0,
      coinsOnPlay: 0, science: null, effect: "1 VP for each Military card present in both neighbouring cities.",
      chainFrom: [], chainTo: [], guildRule: { kind: "countCardType", cardType: "military", scope: "neighbors", per: 1 } },
    { id: "magistrates-guild", name: "Magistrates Guild", emoji: "⚖️", age: 3, type: "guild",
      cost: { stone: 2, wood: 1, loom: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0,
      coinsOnPlay: 0, science: null, effect: "1 VP for each Civilian card present in both neighbouring cities.",
      chainFrom: [], chainTo: [], guildRule: { kind: "countCardType", cardType: "civilian", scope: "neighbors", per: 1 } },
    { id: "workers-guild", name: "Workers Guild", emoji: "👷", age: 3, type: "guild",
      cost: { ore: 2, clay: 1, stone: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0,
      coinsOnPlay: 0, science: null, effect: "1 VP for each Raw Material card present in both neighbouring cities.",
      chainFrom: [], chainTo: [], guildRule: { kind: "countCardType", cardType: "raw", scope: "neighbors", per: 1 } },
    { id: "craftsmens-guild", name: "Craftsmens Guild", emoji: "🛠️", age: 3, type: "guild",
      cost: { ore: 2, stone: 2 }, produces: [], producesChoice: false, vp: 0, shields: 0,
      coinsOnPlay: 0, science: null, effect: "2 VP for each Manufactured Good card present in both neighbouring cities.",
      chainFrom: [], chainTo: [], guildRule: { kind: "countCardType", cardType: "manufactured", scope: "neighbors", per: 2 } },
    { id: "traders-guild", name: "Traders Guild", emoji: "🧳", age: 3, type: "guild",
      cost: { loom: 1, papyrus: 1, glass: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0,
      coinsOnPlay: 0, science: null, effect: "1 VP for each Commercial card present in both neighbouring cities.",
      chainFrom: [], chainTo: [], guildRule: { kind: "countCardType", cardType: "commercial", scope: "neighbors", per: 1 } },
    { id: "philosophers-guild", name: "Philosophers Guild", emoji: "📖", age: 3, type: "guild",
      cost: { clay: 3, loom: 1, papyrus: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0,
      coinsOnPlay: 0, science: null, effect: "1 VP for each Scientific card present in both neighbouring cities.",
      chainFrom: [], chainTo: [], guildRule: { kind: "countCardType", cardType: "scientific", scope: "neighbors", per: 1 } },
    { id: "builders-guild", name: "Builders Guild", emoji: "🏗️", age: 3, type: "guild",
      cost: { stone: 2, clay: 2, glass: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0,
      coinsOnPlay: 0, science: null, effect: "1 VP for each Wonder stage built in the neighbouring cities and in your own city.",
      chainFrom: [], chainTo: [], guildRule: { kind: "countWonderStages", scope: "neighborsAndSelf", per: 1 } },
    { id: "shipowners-guild", name: "Shipowners Guild", emoji: "🚢", age: 3, type: "guild",
      cost: { wood: 3, papyrus: 1, glass: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0,
      coinsOnPlay: 0, science: null, effect: "1 VP for each Raw Material, Manufactured Good, and Guild card in your city.",
      chainFrom: [], chainTo: [], guildRule: { kind: "countCardTypes", cardTypes: ["raw", "manufactured", "guild"], scope: "self", per: 1 } },
    { id: "strategists-guild", name: "Strategists Guild", emoji: "🎖️", age: 3, type: "guild",
      cost: { ore: 2, stone: 1, loom: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0,
      coinsOnPlay: 0, science: null, effect: "1 VP for each defeat token present in the neighbouring cities.",
      chainFrom: [], chainTo: [], guildRule: { kind: "countDefeatTokens", scope: "neighbors", per: 1 } },
    { id: "scientists-guild", name: "Scientists Guild", emoji: "🔬", age: 3, type: "guild",
      cost: { wood: 2, ore: 2, papyrus: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0,
      coinsOnPlay: 0, science: null, effect: "Gain an extra scientific symbol of your choice.",
      chainFrom: [], chainTo: [], special: "extraScienceSymbol" },
  ],
};

if (typeof module !== "undefined" && module.exports) module.exports = GameData;
