// 7 Wonders — static game data (card types, resources, cards, Wonder boards). Loaded before
// script.js. This is the file admin/index.html edits and re-exports — keep all content data
// here, keep logic in script.js. See docs/requirements.md §3/§3b for the data shapes.
//
// Types (Card, WonderBoard, GameDataShape, etc.) come from src/types.d.ts, visible here as global
// ambient declarations with no import — see that file's header for why.
"use strict";
const GameData = {
    CARD_TYPES: {
        basic: { label: "Raw Material", color: "#D4A453", colorDim: "#6B4423" },
        manufactured: { label: "Manufactured Good", color: "#808080", colorDim: "#454a52" },
        civilian: { label: "Civilian Structure", color: "#0051FF", colorDim: "#22384a" },
        scientific: { label: "Scientific Structure", color: "#00DD77", colorDim: "#22402c" },
        commercial: { label: "Commercial Structure", color: "#FBBF24", colorDim: "#4a3d1e" },
        military: { label: "Military Structure", color: "#FF2222", colorDim: "#4a2226" },
        guild: { label: "Guild", color: "#A855F7", colorDim: "#3a2a49" },
    },
    // `icon` is the illustrated artwork (game/images/icons/); `emoji` stays as a fallback for
    // contexts that can't render an <img> (e.g. admin.html's raw JSON view) and as short
    // alt/title text — see script.js's resIcon()/sciIcon() helpers.
    RESOURCES: {
        wood: { label: "Wood", emoji: "🪵", icon: "images/icons/res-wood.png" },
        clay: { label: "Clay", emoji: "🧱", icon: "images/icons/res-clay.png" },
        ore: { label: "Ore", emoji: "⛏️", icon: "images/icons/res-ore.png" },
        stone: { label: "Stone", emoji: "🪨", icon: "images/icons/res-stone.png" },
        glass: { label: "Glass", emoji: "🔷", icon: "images/icons/res-glass.png" },
        loom: { label: "Loom", emoji: "🧵", icon: "images/icons/res-loom.png" },
        papyrus: { label: "Papyrus", emoji: "📜", icon: "images/icons/res-papyrus.png" },
    },
    SCIENCE_SYMBOLS: {
        tablet: { label: "Tablet", emoji: "📚", icon: "images/icons/sym-tablet.png" },
        compass: { label: "Compass", emoji: "🧭", icon: "images/icons/sym-compass.png" },
        gear: { label: "Gear", emoji: "⚙️", icon: "images/icons/sym-gear.png" },
    },
    // Non-resource illustrated icons, same provenance/rationale as RESOURCES/SCIENCE_SYMBOLS above.
    ICONS: {
        vp: "images/icons/sym-vp.png", // laurel wreath — victory points
        coins: "images/icons/sym-coins.png", // gold coin
        shields: "images/icons/sym-shields.png", // crossed swords on a shield — military strength
        chain: "images/icons/sym-chain.png", // carved arrow — free-build chain unlock
        conflict: "images/icons/sym-conflict.png", // helmet + shield + arrows — military conflict resolution
        wonder: "images/icons/sym-wonder.png", // pyramid — generic "Wonder" glyph
    },
    // Individual card and scene images, organized by age. Each card/scene has its own file.
    // Card images are stored in:
    //   - images/cards/age1/ (All Age I cards - production, civic, trade, military, science)
    //   - images/cards/age2/ (All Age II cards)
    //   - images/cards/age3/ (All Age III cards)
    //   - images/wonders/ (Wonder board images)
    // Scene images are in:
    //   - images/scenes/ (screen background artwork)
    CARD_IMAGES: {
        // Age I cards (28 total)
        "lumber-yard": "images/cards/age1/lumber-yard.png",
        "forest-cave": "images/cards/age1/forest-cave.png",
        "ore-vein": "images/cards/age1/ore-vein.png",
        "mine": "images/cards/age1/mine.png",
        "clay-pool": "images/cards/age1/clay-pool.png",
        "clay-pit": "images/cards/age1/clay-pit.png",
        "stone-pit": "images/cards/age1/stone-pit.png",
        "quarry": "images/cards/age1/quarry.png",
        "glassworks": "images/cards/age1/glassworks.png",
        "press": "images/cards/age1/press.png",
        "loom": "images/cards/age1/loom-house.png",
        "scriptorium": "images/cards/age1/scriptorium.png",
        "workshop": "images/cards/age1/workshop.png",
        "apothecary": "images/cards/age1/apothecary.png",
        "baths": "images/cards/age1/baths.png",
        "altar": "images/cards/age1/altar.png",
        "theater": "images/cards/age1/theater.png",
        "well": "images/cards/age1/well.png",
        "shrine": "images/cards/age1/shrine.png",
        "statue-garden": "images/cards/age1/statue-garden.png",
        "plaza": "images/cards/age1/plaza.png",
        "tavern": "images/cards/age1/tavern.png",
        "market": "images/cards/age1/market.png",
        "trading-post": "images/cards/age1/trading-post.png",
        "caravanserai": "images/cards/age1/caravanserai.png",
        "stockade": "images/cards/age1/stockade.png",
        "garrison": "images/cards/age1/garrison.png",
        "barracks": "images/cards/age1/barracks.png",
        // Age I cards added by the docs/card-reference.html transcription (real names not covered
        // by the placeholder art above) — generated via .claude/skills/image-generation
        "timber-yard": "images/cards/age1/timber-yard.png",
        "excavation": "images/cards/age1/excavation.png",
        "tree-farm": "images/cards/age1/tree-farm.png",
        "west-trading-post": "images/cards/age1/west-trading-post.png",
        "east-trading-post": "images/cards/age1/east-trading-post.png",
        "marketplace": "images/cards/age1/marketplace.png",
        "guard-tower": "images/cards/age1/guard-tower.png",
        // Age II cards (28 total)
        "sawmill": "images/cards/age2/sawmill.png",
        "foundry": "images/cards/age2/foundry.png",
        "brickyard": "images/cards/age2/brickyard.png",
        "shelf-quarry": "images/cards/age2/shelf-quarry.png",
        "caravan": "images/cards/age2/caravan.png",
        "glassworks-3": "images/cards/age2/stained-glass-works.png",
        "glassworks-4": "images/cards/age2/stained-glass-works.png",
        "press-3": "images/cards/age2/papyrus-mill.png",
        "press-4": "images/cards/age2/papyrus-mill.png",
        "loom-3": "images/cards/age2/loom-shed.png",
        "loom-4": "images/cards/age2/loom-shed.png",
        "bazaar": "images/cards/age2/bazaar.png",
        "customs-house": "images/cards/age2/customs-house.png",
        "forum-market": "images/cards/age2/forum-market.png",
        "guild-exchange": "images/cards/age2/guild-exchange.png",
        "dockyard": "images/cards/age2/dockyard.png",
        "bank": "images/cards/age2/bank.png",
        "aqueduct": "images/cards/age2/aqueduct.png",
        "temple": "images/cards/age2/temple.png",
        "statue": "images/cards/age2/statue.png",
        "courtyard": "images/cards/age2/courtyard.png",
        "gardens": "images/cards/age2/gardens.png",
        "senate": "images/cards/age2/senate.png",
        "forum-hall": "images/cards/age2/forum-hall.png",
        "amphitheater": "images/cards/age2/amphitheater.png",
        "courthouse": "images/cards/age2/courthouse.png",
        "observatory": "images/cards/age2/observatory.png",
        "pharmacy": "images/cards/age2/pharmacy.png",
        "walls": "images/cards/age2/walls.png",
        "archery-range": "images/cards/age2/archery-range.png",
        "training-ground": "images/cards/age2/training-ground.png",
        // Age II cards added by the docs/card-reference.html transcription (real names not covered
        // by the placeholder art above) — generated via .claude/skills/image-generation
        "caravansery": "images/cards/age2/caravansery.png",
        "forum": "images/cards/age2/forum.png",
        "vineyard": "images/cards/age2/vineyard.png",
        "stables": "images/cards/age2/stables.png",
        "dispensary": "images/cards/age2/dispensary.png",
        "laboratory": "images/cards/age2/laboratory.png",
        "school": "images/cards/age2/school.png",
        // Age III cards (32 total: 15 regular + 10 guilds + 7 special)
        "pantheon": "images/cards/age3/pantheon.png",
        "gardens-palace": "images/cards/age3/gardens-palace.png",
        "town-hall": "images/cards/age3/town-hall.png",
        "palace": "images/cards/age3/palace.png",
        "obelisk": "images/cards/age3/obelisk.png",
        "senate-hall": "images/cards/age3/senate-hall.png",
        "grand-arena": "images/cards/age3/grand-arena.png",
        "university": "images/cards/age3/university.png",
        "library": "images/cards/age3/library.png",
        "monument": "images/cards/age3/monument.png",
        "sanctuary": "images/cards/age3/sanctuary.png",
        "grand-temple": "images/cards/age3/grand-temple.png",
        "fortress": "images/cards/age3/fortress.png",
        "siege-camp": "images/cards/age3/siege-camp.png",
        "citadel": "images/cards/age3/citadel.png",
        "arsenal": "images/cards/age3/arsenal.png",
        "haven": "images/cards/age3/haven.png",
        "lighthouse": "images/cards/age3/lighthouse.png",
        "chamber-of-commerce": "images/cards/age3/chamber-of-commerce.png",
        "university-of-science": "images/cards/age3/university-of-science.png",
        "observatory-tower": "images/cards/age3/observatory-tower.png",
        "lodge": "images/cards/age3/lodge.png",
        // Age III cards added by the docs/card-reference.html transcription (real names not covered
        // by the placeholder art above) — generated via .claude/skills/image-generation
        "ludus": "images/cards/age3/ludus.png",
        "arena": "images/cards/age3/arena.png",
        "decorators-guild": "images/cards/age3/decorators-guild.png",
        "siege-workshop": "images/cards/age3/siege-workshop.png",
        "fortifications": "images/cards/age3/fortifications.png",
        "circus": "images/cards/age3/circus.png",
        "castrum": "images/cards/age3/castrum.png",
        "study": "images/cards/age3/study.png",
        "academy": "images/cards/age3/academy.png",
        // Filler cards (not in base game, generated for spritesheet completeness)
        "marble-quarry": "images/cards/age3/marble-quarry.png",
        "glass-blowers": "images/cards/age3/glass-blowers.png",
        "metal-foundry": "images/cards/age3/metal-foundry.png",
        "silk-workshops": "images/cards/age3/silk-workshops.png",
        "military-academy": "images/cards/age3/military-academy.png",
        "merchant-house": "images/cards/age3/merchant-house.png",
        "temple-gardens": "images/cards/age3/temple-gardens.png",
        "engineers-workshop": "images/cards/age3/engineers-workshop.png",
        "harbor-tower": "images/cards/age3/harbor-tower.png",
        // Age III Guild cards (10 total)
        "spies-guild": "images/cards/age3/spies-guild.png",
        "magistrates-guild": "images/cards/age3/magistrates-guild.png",
        "workers-guild": "images/cards/age3/workers-guild.png",
        "craftsmens-guild": "images/cards/age3/craftsmens-guild.png",
        "traders-guild": "images/cards/age3/traders-guild.png",
        "philosophers-guild": "images/cards/age3/philosophers-guild.png",
        "builders-guild": "images/cards/age3/builders-guild.png",
        "shipowners-guild": "images/cards/age3/shipowners-guild.png",
        "strategists-guild": "images/cards/age3/strategists-guild.png",
        "scientists-guild": "images/cards/age3/scientists-guild.png",
        // Extra content for 5-7 player games (src/game-data.ts §"Age I/II/III extra content") —
        // reuses an existing thematically-similar image rather than commissioning new art.
        "lumber-camp": "images/cards/age1/lumber-yard.png",
        "copper-mine": "images/cards/age1/ore-vein.png",
        "clay-flats": "images/cards/age1/clay-pool.png",
        "loom-croft": "images/cards/age1/loom-house.png",
        "meeting-hall": "images/cards/age1/theater.png",
        "scholars-nook": "images/cards/age1/scriptorium.png",
        "watch-post": "images/cards/age1/stockade.png",
        "granite-pit": "images/cards/age1/stone-pit.png",
        "birch-grove": "images/cards/age1/forest-cave.png",
        "tin-vein": "images/cards/age1/mine.png",
        "glass-shed": "images/cards/age1/glassworks.png",
        "public-bath": "images/cards/age1/altar.png",
        "survey-post": "images/cards/age1/workshop.png",
        "palisade": "images/cards/age1/garrison.png",
        "clay-terrace": "images/cards/age1/clay-pit.png",
        "pine-camp": "images/cards/age1/lumber-yard.png",
        "quartz-mine": "images/cards/age1/ore-vein.png",
        "papyrus-hut": "images/cards/age1/press.png",
        "garden-shrine": "images/cards/age1/shrine.png",
        "archive-room": "images/cards/age1/apothecary.png",
        "sentry-tower": "images/cards/age1/barracks.png",
        "log-mill": "images/cards/age2/sawmill.png",
        "smeltery": "images/cards/age2/foundry.png",
        "clay-works": "images/cards/age2/brickyard.png",
        "dye-mill": "images/cards/age2/loom-shed.png",
        "plaza-hall": "images/cards/age2/courtyard.png",
        "study-hall": "images/cards/age2/courthouse.png",
        "garrison-wall": "images/cards/age2/walls.png",
        "quarry-camp": "images/cards/age2/shelf-quarry.png",
        "grove-mill": "images/cards/age2/sawmill.png",
        "ore-works": "images/cards/age2/foundry.png",
        "glass-foundry": "images/cards/age2/stained-glass-works.png",
        "civic-hall": "images/cards/age2/statue.png",
        "watch-tower": "images/cards/age2/observatory.png",
        "rampart": "images/cards/age2/archery-range.png",
        "silt-pit": "images/cards/age2/brickyard.png",
        "pine-mill": "images/cards/age2/sawmill.png",
        "stone-works": "images/cards/age2/shelf-quarry.png",
        "papyrus-hall": "images/cards/age2/papyrus-mill.png",
        "forum-annex": "images/cards/age2/forum-hall.png",
        "workshop-hall": "images/cards/age2/pharmacy.png",
        "training-yard": "images/cards/age2/training-ground.png",
        "grand-plaza": "images/cards/age3/gardens-palace.png",
        "market-row": "images/cards/age3/chamber-of-commerce.png",
        "bastion": "images/cards/age3/fortress.png",
        "regal-court": "images/cards/age3/palace.png",
        "counting-house": "images/cards/age3/haven.png",
        "grand-academy": "images/cards/age3/university-of-science.png",
        "monumental-arch": "images/cards/age3/monument.png",
        "hall-of-scholars": "images/cards/age3/library.png",
        "chart-house": "images/cards/age3/lodge.png",
    },
    WONDER_IMAGES: {
        "gizah": "images/wonders/gizah.png",
        "rhodos": "images/wonders/rhodos.png",
        "ephesos": "images/wonders/ephesos.png",
        "babylon": "images/wonders/babylon.png",
        "olympia": "images/wonders/olympia.png",
        "halikarnassos": "images/wonders/halikarnassos.png",
        "alexandria": "images/wonders/alexandria.png",
    },
    // Scene images for screens and panels
    SCENES: {
        // Age I scenes
        wonderBuild: "images/scenes/wonderBuild.png",
        discardPile: "images/scenes/discardPile.png",
        finalTriumph: "images/scenes/finalTriumph.png",
        battlefield: "images/scenes/battlefield.png",
        // Age II scenes
        defeat: "images/scenes/defeat.png",
        guildHall: "images/scenes/guildHall.png",
        wonderComplete: "images/scenes/wonderComplete.png",
        ageDawn: "images/scenes/ageDawn.png",
        // Age III scenes
        finalVictory: "images/scenes/final-victory.png",
    },
    // Illustration art for card faces (game/images/): CARD_IMAGES above covers every card `id` that
    // existed when those files were generated. The CARDS rewrite transcribing docs/card-reference.html
    // (real names/ids) left about a third of ids without a matching CARD_IMAGES entry — some
    // (duplicate-copy ids like "stone-pit-2") fall back to their base id's image via script.js's
    // cardImagePath(); the rest (real cards that simply didn't exist under the old placeholder
    // names — Timber Yard, West/East Trading Post, Ludus, Dispensary, ...) have no image yet and
    // fall all the way through to this pool, hashed per-card by script.js's cardArtUrl() — empty
    // for now, so those cards render their emoji badge only until art is generated for them (see
    // AGENTS.md "Generating a card image").
    CARD_ART: {
        pool: [],
    },
    // Base game only — the Leaders expansion and the 2-player "Free City" variant (see
    // docs/rules.md) are not implemented. Each card carries a `playerCount`: the smallest table it
    // appears at, so `playerCount <= numPlayers` selects the deck. Player counts 3-4 use the base
    // ~90-card pool; 5-7 layer in the "extra content" blocks below (`playerCount` 5/6/7) so every
    // Age still deals exactly 7 cards per player at every offered count — an Age needs 7×players
    // cards, and the physical game covers that at higher counts by adding extra copies, mostly of
    // basic resource cards. This implementation follows the same idea but with original placeholder
    // cards rather than duplicate copies of the base ones (see the per-block comments); like the
    // base pool, they're a representative sample, not the authoritative physical scaling. Guild
    // count is never the bottleneck: 10 exist and at most `numPlayers + 2` (9, at 7 players) are
    // ever needed. `buildDeckPools` throws rather than dealing a short pool, so a miscounted tier
    // fails loudly instead of silently shipping short hands.
    SUPPORTED_PLAYER_COUNTS: [3, 4, 5, 6, 7],
    // Human-readable text for each `effect.power` a Wonder stage can grant (keys match the
    // `power` strings used in WONDERS below). Kept as data so the UI never hard-codes rule text.
    WONDER_POWERS: {
        produceRawChoice: "Each turn, produce 1 raw material of your choice (Stone/Clay/Wood/Ore). Neighbors cannot buy it.",
        produceManufacturedChoice: "Each turn, produce 1 manufactured good of your choice (Glass/Loom/Papyrus). Neighbors cannot buy it.",
        extraScienceSymbol: "At the end of the game, gain an extra scientific symbol of your choice.",
        freeBuildPerAge: "Once per Age, construct a structure from your hand for free.",
        discardPileBuild: "Look through every card discarded since the start of the game, pick one, and build it for free.",
        lastCardAlternative: "Play the 7th card of each Age instead of discarding it (build it, discard it for 3 coins, or use it on your Wonder).",
        cheapRawTrade: "Buy raw materials from both neighboring cities for 1 coin instead of 2.",
        copyNeighborGuild: "At the end of the game, copy one Guild (purple card) built by either neighboring city.",
    },
    // The seven Wonder boards, transcribed from the board scans and rule text in
    // docs/wonders_boards/*.png. Each board has a starting `resource` (produced free from turn 1,
    // and purchasable by neighbours like any other production) and two playable faces:
    // `sides.A` (the simple face) and `sides.B` (the advanced face). Every side is a list of
    // stages built strictly left-to-right, each `{ cost, effect }`; `effect` may carry any of
    // `vp` / `coins` / `shields` / `power` (see WONDER_POWERS above). Gizah's B face is the one
    // board with 4 stages — nothing may assume a fixed stage count.
    //
    // Unlike CARDS below, this data *is* transcribed from the physical boards, not placeholder.
    WONDERS: [
        {
            id: "gizah", name: "Gizah", emoji: "🔺", resource: "stone",
            sides: {
                A: {
                    summary: "No special ability — the three stages are worth 3, 5 and 7 victory points.",
                    stages: [
                        { cost: { stone: 2 }, effect: { vp: 3 } },
                        { cost: { wood: 3 }, effect: { vp: 5 } },
                        { cost: { stone: 4 }, effect: { vp: 7 } },
                    ],
                },
                B: {
                    summary: "Built in 4 stages worth 3, 5, 5 and 7 victory points — 20 points in total.",
                    stages: [
                        { cost: { wood: 2 }, effect: { vp: 3 } },
                        { cost: { stone: 3 }, effect: { vp: 5 } },
                        { cost: { clay: 3 }, effect: { vp: 5 } },
                        { cost: { stone: 4, papyrus: 1 }, effect: { vp: 7 } },
                    ],
                },
            },
        },
        {
            id: "rhodos", name: "Rhodos", emoji: "🗿", resource: "ore",
            sides: {
                A: {
                    summary: "The second stage adds 2 Shields to your strength in every conflict resolution.",
                    stages: [
                        { cost: { wood: 2 }, effect: { vp: 3 } },
                        { cost: { clay: 3 }, effect: { shields: 2 } },
                        { cost: { ore: 4 }, effect: { vp: 7 } },
                    ],
                },
                B: {
                    summary: "The Colossus is built in only 2 stages, each worth 1 Shield, coins and victory points.",
                    stages: [
                        { cost: { stone: 3 }, effect: { shields: 1, coins: 3, vp: 3 } },
                        { cost: { ore: 4 }, effect: { shields: 1, coins: 4, vp: 4 } },
                    ],
                },
            },
        },
        {
            id: "ephesos", name: "Ephesos", emoji: "🛕", resource: "papyrus",
            sides: {
                A: {
                    summary: "The second stage pays 9 coins from the bank, once, as soon as it is built.",
                    stages: [
                        { cost: { stone: 2 }, effect: { vp: 3 } },
                        { cost: { wood: 2 }, effect: { coins: 9 } },
                        { cost: { papyrus: 2 }, effect: { vp: 7 } },
                    ],
                },
                B: {
                    summary: "Every stage pays 4 coins from the bank, once, as soon as it is built.",
                    stages: [
                        { cost: { stone: 2 }, effect: { vp: 2, coins: 4 } },
                        { cost: { wood: 2 }, effect: { vp: 3, coins: 4 } },
                        { cost: { papyrus: 1, loom: 1, glass: 1 }, effect: { vp: 5, coins: 4 } },
                    ],
                },
            },
        },
        {
            id: "babylon", name: "Babylon", emoji: "🌳", resource: "clay",
            sides: {
                A: {
                    summary: "The second stage grants an extra scientific symbol, chosen at the end of the game.",
                    stages: [
                        { cost: { clay: 2 }, effect: { vp: 3 } },
                        { cost: { wood: 3 }, effect: { power: "extraScienceSymbol" } },
                        { cost: { clay: 4 }, effect: { vp: 7 } },
                    ],
                },
                B: {
                    summary: "The second stage lets you play the 7th card of each Age; the third grants a scientific symbol of your choice.",
                    stages: [
                        { cost: { loom: 1, clay: 1 }, effect: { vp: 3 } },
                        { cost: { glass: 1, wood: 2 }, effect: { power: "lastCardAlternative" } },
                        { cost: { clay: 4, papyrus: 1 }, effect: { power: "extraScienceSymbol" } },
                    ],
                },
            },
        },
        {
            id: "olympia", name: "Olympia", emoji: "🏟️", resource: "wood",
            sides: {
                A: {
                    summary: "The second stage lets you build one structure for free, once per Age.",
                    stages: [
                        { cost: { wood: 2 }, effect: { vp: 3 } },
                        { cost: { stone: 2 }, effect: { power: "freeBuildPerAge" } },
                        { cost: { ore: 2 }, effect: { vp: 7 } },
                    ],
                },
                B: {
                    summary: "Cheap raw materials from both neighbors, then 5 VP, then a copy of a neighboring Guild.",
                    stages: [
                        { cost: { wood: 2 }, effect: { power: "cheapRawTrade" } },
                        { cost: { stone: 2 }, effect: { vp: 5 } },
                        { cost: { loom: 1, ore: 2 }, effect: { power: "copyNeighborGuild" } },
                    ],
                },
            },
        },
        {
            id: "halikarnassos", name: "Halikarnassos", emoji: "⚰️", resource: "loom",
            sides: {
                A: {
                    summary: "The second stage lets you build one card from the discard pile for free.",
                    stages: [
                        { cost: { clay: 2 }, effect: { vp: 3 } },
                        { cost: { ore: 3 }, effect: { power: "discardPileBuild" } },
                        { cost: { loom: 2 }, effect: { vp: 7 } },
                    ],
                },
                B: {
                    summary: "Every stage lets you build another card from the discard pile for free.",
                    stages: [
                        { cost: { ore: 2 }, effect: { vp: 2, power: "discardPileBuild" } },
                        { cost: { clay: 3 }, effect: { vp: 1, power: "discardPileBuild" } },
                        { cost: { glass: 1, papyrus: 1, loom: 1 }, effect: { power: "discardPileBuild" } },
                    ],
                },
            },
        },
        {
            id: "alexandria", name: "Alexandria", emoji: "🗼", resource: "glass",
            sides: {
                A: {
                    summary: "The second stage produces one raw material of your choice every turn.",
                    stages: [
                        { cost: { stone: 2 }, effect: { vp: 3 } },
                        { cost: { ore: 2 }, effect: { power: "produceRawChoice" } },
                        { cost: { glass: 2 }, effect: { vp: 7 } },
                    ],
                },
                B: {
                    summary: "A raw material of your choice each turn, then a manufactured good of your choice, then 7 VP.",
                    stages: [
                        { cost: { clay: 2 }, effect: { power: "produceRawChoice" } },
                        { cost: { wood: 2 }, effect: { power: "produceManufacturedChoice" } },
                        { cost: { stone: 3 }, effect: { vp: 7 } },
                    ],
                },
            },
        },
    ],
    // Card pool — transcribed from docs/card-reference.html (base-game names, costs, VP/shields/
    // science, and per-player-count copy scaling), verified against buildDeckPools' requirement
    // that the valid pool hold >= 7×numPlayers cards per Age (6×numPlayers-2 non-Guild for Age III,
    // Guilds kept separately at `numPlayers + 2` per docs/rules.md). A card with more than one
    // checkmark in the reference's player-count columns (e.g. Stone Pit, in the deck at 3+ and
    // again at 5+) becomes multiple entries here sharing the same name/cost/effect, one per copy,
    // each with its own `playerCount` threshold and a numeric id suffix (`stone-pit`, `stone-pit-2`,
    // ...) — CARD_BY_ID and buildDeckPools both key off `id`, so distinct ids are required even
    // though the copies are otherwise identical. Chain pairs (chainFrom/chainTo — not in
    // docs/card-reference.html or docs/rules.md/rules_per_age/*.png, since the chain arrows are a
    // physical-card detail) came from the developer directly rather than either transcription; a
    // chain target's chainFrom lists *every* duplicate-copy id of its precursor(s) (building any
    // copy satisfies the chain), and a source's chainTo likewise lists every copy id of its
    // target(s) — script.ts's formatChainList strips the copy suffix and dedupes before display, so
    // the UI still reads "Baths" rather than "Baths, Baths 2". Age II Grey cards (Glassworks/Press/
    // Loom) share their Age I counterparts' name, per the developer — the reference table's shared-
    // name row with separate Age I/II copy counts reflects that they're the same-named card, not a
    // distinct Age II name; their ids continue the same copy-suffix numbering across both ages
    // (`glassworks`/`glassworks-2` in Age I, `glassworks-3`/`glassworks-4` in Age II) since `id`
    // must stay unique per CARD_BY_ID/buildDeckPools even though `name` repeats.
    CARDS: [
        // ---- Age I/II Brown (Raw Materials) — transcribed from docs/card-reference.html ----
        { id: "lumber-yard", name: "Lumber Yard", emoji: "🪵", age: 1, type: "basic",
            cost: {}, produces: ["wood"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Produces 1 Wood.",
            chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "lumber-yard-2", name: "Lumber Yard", emoji: "🪵", age: 1, type: "basic",
            cost: {}, produces: ["wood"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Produces 1 Wood.",
            chainFrom: [], chainTo: [], playerCount: 4 },
        { id: "ore-vein", name: "Ore Vein", emoji: "⛏️", age: 1, type: "basic",
            cost: {}, produces: ["ore"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Produces 1 Ore.",
            chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "ore-vein-2", name: "Ore Vein", emoji: "⛏️", age: 1, type: "basic",
            cost: {}, produces: ["ore"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Produces 1 Ore.",
            chainFrom: [], chainTo: [], playerCount: 4 },
        { id: "stone-pit", name: "Stone Pit", emoji: "🪨", age: 1, type: "basic",
            cost: {}, produces: ["stone"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Produces 1 Stone.",
            chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "stone-pit-2", name: "Stone Pit", emoji: "🪨", age: 1, type: "basic",
            cost: {}, produces: ["stone"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Produces 1 Stone.",
            chainFrom: [], chainTo: [], playerCount: 5 },
        { id: "clay-pool", name: "Clay Pool", emoji: "🧱", age: 1, type: "basic",
            cost: {}, produces: ["clay"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Produces 1 Clay.",
            chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "clay-pool-2", name: "Clay Pool", emoji: "🧱", age: 1, type: "basic",
            cost: {}, produces: ["clay"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Produces 1 Clay.",
            chainFrom: [], chainTo: [], playerCount: 5 },
        { id: "timber-yard", name: "Timber Yard", emoji: "🪵", age: 1, type: "basic",
            cost: { coins: 1 }, produces: ["wood", "stone"], producesChoice: true, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Produces 1 of your choice: Wood or Stone.",
            chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "clay-pit", name: "Clay Pit", emoji: "🧱", age: 1, type: "basic",
            cost: { coins: 1 }, produces: ["ore", "clay"], producesChoice: true, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Produces 1 of your choice: Ore or Clay.",
            chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "excavation", name: "Excavation", emoji: "⛏️", age: 1, type: "basic",
            cost: { coins: 1 }, produces: ["stone", "clay"], producesChoice: true, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Produces 1 of your choice: Stone or Clay.",
            chainFrom: [], chainTo: [], playerCount: 4 },
        { id: "forest-cave", name: "Forest Cave", emoji: "🌲", age: 1, type: "basic",
            cost: { coins: 1 }, produces: ["wood", "ore"], producesChoice: true, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Produces 1 of your choice: Wood or Ore.",
            chainFrom: [], chainTo: [], playerCount: 5 },
        { id: "tree-farm", name: "Tree Farm", emoji: "🌳", age: 1, type: "basic",
            cost: { coins: 1 }, produces: ["wood", "clay"], producesChoice: true, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Produces 1 of your choice: Wood or Clay.",
            chainFrom: [], chainTo: [], playerCount: 6 },
        { id: "mine", name: "Mine", emoji: "⛰️", age: 1, type: "basic",
            cost: { coins: 1 }, produces: ["stone", "ore"], producesChoice: true, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Produces 1 of your choice: Stone or Ore.",
            chainFrom: [], chainTo: [], playerCount: 6 },
        { id: "sawmill", name: "Sawmill", emoji: "🪚", age: 2, type: "basic",
            cost: { coins: 1 }, produces: ["wood"], producesChoice: false, produceCount: 2, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Produces 2 Wood.",
            chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "sawmill-2", name: "Sawmill", emoji: "🪚", age: 2, type: "basic",
            cost: { coins: 1 }, produces: ["wood"], producesChoice: false, produceCount: 2, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Produces 2 Wood.",
            chainFrom: [], chainTo: [], playerCount: 4 },
        { id: "foundry", name: "Foundry", emoji: "🔥", age: 2, type: "basic",
            cost: { coins: 1 }, produces: ["ore"], producesChoice: false, produceCount: 2, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Produces 2 Ore.",
            chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "foundry-2", name: "Foundry", emoji: "🔥", age: 2, type: "basic",
            cost: { coins: 1 }, produces: ["ore"], producesChoice: false, produceCount: 2, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Produces 2 Ore.",
            chainFrom: [], chainTo: [], playerCount: 4 },
        { id: "quarry", name: "Quarry", emoji: "🪨", age: 2, type: "basic",
            cost: { coins: 1 }, produces: ["stone"], producesChoice: false, produceCount: 2, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Produces 2 Stone.",
            chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "quarry-2", name: "Quarry", emoji: "🪨", age: 2, type: "basic",
            cost: { coins: 1 }, produces: ["stone"], producesChoice: false, produceCount: 2, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Produces 2 Stone.",
            chainFrom: [], chainTo: [], playerCount: 4 },
        { id: "brickyard", name: "Brickyard", emoji: "🧱", age: 2, type: "basic",
            cost: { coins: 1 }, produces: ["clay"], producesChoice: false, produceCount: 2, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Produces 2 Clay.",
            chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "brickyard-2", name: "Brickyard", emoji: "🧱", age: 2, type: "basic",
            cost: { coins: 1 }, produces: ["clay"], producesChoice: false, produceCount: 2, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Produces 2 Clay.",
            chainFrom: [], chainTo: [], playerCount: 4 },
        // ---- Age I Grey (Manufactured Goods) ----
        { id: "glassworks", name: "Glassworks", emoji: "🔷", age: 1, type: "manufactured",
            cost: {}, produces: ["glass"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Produces 1 Glass.",
            chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "glassworks-2", name: "Glassworks", emoji: "🔷", age: 1, type: "manufactured",
            cost: {}, produces: ["glass"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Produces 1 Glass.",
            chainFrom: [], chainTo: [], playerCount: 6 },
        { id: "press", name: "Press", emoji: "📜", age: 1, type: "manufactured",
            cost: {}, produces: ["papyrus"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Produces 1 Papyrus.",
            chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "press-2", name: "Press", emoji: "📜", age: 1, type: "manufactured",
            cost: {}, produces: ["papyrus"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Produces 1 Papyrus.",
            chainFrom: [], chainTo: [], playerCount: 6 },
        { id: "loom", name: "Loom", emoji: "🧵", age: 1, type: "manufactured",
            cost: {}, produces: ["loom"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Produces 1 Loom.",
            chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "loom-2", name: "Loom", emoji: "🧵", age: 1, type: "manufactured",
            cost: {}, produces: ["loom"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Produces 1 Loom.",
            chainFrom: [], chainTo: [], playerCount: 6 },
        // ---- Age II Grey (Manufactured Goods) — same names as Age I (Glassworks/Press/Loom); the
        // reference table shows Age I/II copy counts under one shared name because they are the same
        // name, not a distinct Age II card name ----
        { id: "glassworks-3", name: "Glassworks", emoji: "🔷", age: 2, type: "manufactured",
            cost: {}, produces: ["glass"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Produces 1 Glass.",
            chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "glassworks-4", name: "Glassworks", emoji: "🔷", age: 2, type: "manufactured",
            cost: {}, produces: ["glass"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Produces 1 Glass.",
            chainFrom: [], chainTo: [], playerCount: 5 },
        { id: "press-3", name: "Press", emoji: "📜", age: 2, type: "manufactured",
            cost: {}, produces: ["papyrus"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Produces 1 Papyrus.",
            chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "press-4", name: "Press", emoji: "📜", age: 2, type: "manufactured",
            cost: {}, produces: ["papyrus"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Produces 1 Papyrus.",
            chainFrom: [], chainTo: [], playerCount: 5 },
        { id: "loom-3", name: "Loom", emoji: "🧵", age: 2, type: "manufactured",
            cost: {}, produces: ["loom"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Produces 1 Loom.",
            chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "loom-4", name: "Loom", emoji: "🧵", age: 2, type: "manufactured",
            cost: {}, produces: ["loom"], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Produces 1 Loom.",
            chainFrom: [], chainTo: [], playerCount: 5 },
        // ---- Blue (Civilian Structures) ----
        { id: "altar", name: "Altar", emoji: "⛩️", age: 1, type: "civilian",
            cost: {}, produces: [], producesChoice: false, vp: 3, shields: 0, coinsOnPlay: 0,
            effect: "Worth 3 VP.",
            chainFrom: [], chainTo: ["temple", "temple-2"], playerCount: 3 },
        { id: "altar-2", name: "Altar", emoji: "⛩️", age: 1, type: "civilian",
            cost: {}, produces: [], producesChoice: false, vp: 3, shields: 0, coinsOnPlay: 0,
            effect: "Worth 3 VP.",
            chainFrom: [], chainTo: ["temple", "temple-2"], playerCount: 5 },
        { id: "theater", name: "Theater", emoji: "🎭", age: 1, type: "civilian",
            cost: {}, produces: [], producesChoice: false, vp: 3, shields: 0, coinsOnPlay: 0,
            effect: "Worth 3 VP.",
            chainFrom: [], chainTo: ["statue", "statue-2"], playerCount: 3 },
        { id: "theater-2", name: "Theater", emoji: "🎭", age: 1, type: "civilian",
            cost: {}, produces: [], producesChoice: false, vp: 3, shields: 0, coinsOnPlay: 0,
            effect: "Worth 3 VP.",
            chainFrom: [], chainTo: ["statue", "statue-2"], playerCount: 6 },
        { id: "well", name: "Well", emoji: "⛲", age: 1, type: "civilian",
            cost: {}, produces: [], producesChoice: false, vp: 3, shields: 0, coinsOnPlay: 0,
            effect: "Worth 3 VP.",
            chainFrom: [], chainTo: [], playerCount: 4 },
        { id: "well-2", name: "Well", emoji: "⛲", age: 1, type: "civilian",
            cost: {}, produces: [], producesChoice: false, vp: 3, shields: 0, coinsOnPlay: 0,
            effect: "Worth 3 VP.",
            chainFrom: [], chainTo: [], playerCount: 7 },
        { id: "baths", name: "Baths", emoji: "🛁", age: 1, type: "civilian",
            cost: { stone: 1 }, produces: [], producesChoice: false, vp: 3, shields: 0, coinsOnPlay: 0,
            effect: "Worth 3 VP.",
            chainFrom: [], chainTo: ["aqueduct", "aqueduct-2"], playerCount: 3 },
        { id: "baths-2", name: "Baths", emoji: "🛁", age: 1, type: "civilian",
            cost: { stone: 1 }, produces: [], producesChoice: false, vp: 3, shields: 0, coinsOnPlay: 0,
            effect: "Worth 3 VP.",
            chainFrom: [], chainTo: ["aqueduct", "aqueduct-2"], playerCount: 7 },
        { id: "courthouse", name: "Courthouse", emoji: "⚖️", age: 2, type: "civilian",
            cost: { clay: 2, loom: 1 }, produces: [], producesChoice: false, vp: 4, shields: 0, coinsOnPlay: 0,
            effect: "Worth 4 VP.",
            chainFrom: ["scriptorium", "scriptorium-2"], chainTo: [], playerCount: 3 },
        { id: "courthouse-2", name: "Courthouse", emoji: "⚖️", age: 2, type: "civilian",
            cost: { clay: 2, loom: 1 }, produces: [], producesChoice: false, vp: 4, shields: 0, coinsOnPlay: 0,
            effect: "Worth 4 VP.",
            chainFrom: ["scriptorium", "scriptorium-2"], chainTo: [], playerCount: 5 },
        { id: "temple", name: "Temple", emoji: "🏯", age: 2, type: "civilian",
            cost: { wood: 1, clay: 1, glass: 1 }, produces: [], producesChoice: false, vp: 4, shields: 0, coinsOnPlay: 0,
            effect: "Worth 4 VP.",
            chainFrom: ["altar", "altar-2"], chainTo: ["pantheon", "pantheon-2"], playerCount: 3 },
        { id: "temple-2", name: "Temple", emoji: "🏯", age: 2, type: "civilian",
            cost: { wood: 1, clay: 1, glass: 1 }, produces: [], producesChoice: false, vp: 4, shields: 0, coinsOnPlay: 0,
            effect: "Worth 4 VP.",
            chainFrom: ["altar", "altar-2"], chainTo: ["pantheon", "pantheon-2"], playerCount: 6 },
        { id: "statue", name: "Statue", emoji: "🗽", age: 2, type: "civilian",
            cost: { wood: 1, ore: 2 }, produces: [], producesChoice: false, vp: 4, shields: 0, coinsOnPlay: 0,
            effect: "Worth 4 VP.",
            chainFrom: ["theater", "theater-2"], chainTo: ["gardens", "gardens-2"], playerCount: 3 },
        { id: "statue-2", name: "Statue", emoji: "🗽", age: 2, type: "civilian",
            cost: { wood: 1, ore: 2 }, produces: [], producesChoice: false, vp: 4, shields: 0, coinsOnPlay: 0,
            effect: "Worth 4 VP.",
            chainFrom: ["theater", "theater-2"], chainTo: ["gardens", "gardens-2"], playerCount: 7 },
        { id: "aqueduct", name: "Aqueduct", emoji: "🌉", age: 2, type: "civilian",
            cost: { stone: 3 }, produces: [], producesChoice: false, vp: 5, shields: 0, coinsOnPlay: 0,
            effect: "Worth 5 VP.",
            chainFrom: ["baths", "baths-2"], chainTo: [], playerCount: 3 },
        { id: "aqueduct-2", name: "Aqueduct", emoji: "🌉", age: 2, type: "civilian",
            cost: { stone: 3 }, produces: [], producesChoice: false, vp: 5, shields: 0, coinsOnPlay: 0,
            effect: "Worth 5 VP.",
            chainFrom: ["baths", "baths-2"], chainTo: [], playerCount: 7 },
        { id: "gardens", name: "Gardens", emoji: "🌺", age: 3, type: "civilian",
            cost: { wood: 2, clay: 1 }, produces: [], producesChoice: false, vp: 5, shields: 0, coinsOnPlay: 0,
            effect: "Worth 5 VP.",
            chainFrom: ["statue", "statue-2"], chainTo: [], playerCount: 3 },
        { id: "gardens-2", name: "Gardens", emoji: "🌺", age: 3, type: "civilian",
            cost: { wood: 2, clay: 1 }, produces: [], producesChoice: false, vp: 5, shields: 0, coinsOnPlay: 0,
            effect: "Worth 5 VP.",
            chainFrom: ["statue", "statue-2"], chainTo: [], playerCount: 4 },
        { id: "senate", name: "Senate", emoji: "🏛️", age: 3, type: "civilian",
            cost: { wood: 2, ore: 1, stone: 1 }, produces: [], producesChoice: false, vp: 6, shields: 0, coinsOnPlay: 0,
            effect: "Worth 6 VP.",
            chainFrom: ["library", "library-2"], chainTo: [], playerCount: 3 },
        { id: "senate-2", name: "Senate", emoji: "🏛️", age: 3, type: "civilian",
            cost: { wood: 2, ore: 1, stone: 1 }, produces: [], producesChoice: false, vp: 6, shields: 0, coinsOnPlay: 0,
            effect: "Worth 6 VP.",
            chainFrom: ["library", "library-2"], chainTo: [], playerCount: 5 },
        { id: "town-hall", name: "Town Hall", emoji: "🏤", age: 3, type: "civilian",
            cost: { stone: 3, glass: 1 }, produces: [], producesChoice: false, vp: 6, shields: 0, coinsOnPlay: 0,
            effect: "Worth 6 VP.",
            chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "town-hall-2", name: "Town Hall", emoji: "🏤", age: 3, type: "civilian",
            cost: { stone: 3, glass: 1 }, produces: [], producesChoice: false, vp: 6, shields: 0, coinsOnPlay: 0,
            effect: "Worth 6 VP.",
            chainFrom: [], chainTo: [], playerCount: 6 },
        { id: "pantheon", name: "Pantheon", emoji: "🕍", age: 3, type: "civilian",
            cost: { clay: 2, ore: 1, glass: 1, loom: 1, papyrus: 1 }, produces: [], producesChoice: false, vp: 7, shields: 0, coinsOnPlay: 0,
            effect: "Worth 7 VP.",
            chainFrom: ["temple", "temple-2"], chainTo: [], playerCount: 3 },
        { id: "pantheon-2", name: "Pantheon", emoji: "🕍", age: 3, type: "civilian",
            cost: { clay: 2, ore: 1, glass: 1, loom: 1, papyrus: 1 }, produces: [], producesChoice: false, vp: 7, shields: 0, coinsOnPlay: 0,
            effect: "Worth 7 VP.",
            chainFrom: ["temple", "temple-2"], chainTo: [], playerCount: 6 },
        { id: "palace", name: "Palace", emoji: "🏰", age: 3, type: "civilian",
            cost: { wood: 1, clay: 1, ore: 1, stone: 1, glass: 1, loom: 1, papyrus: 1 }, produces: [], producesChoice: false, vp: 8, shields: 0, coinsOnPlay: 0,
            effect: "Worth 8 VP.",
            chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "palace-2", name: "Palace", emoji: "🏰", age: 3, type: "civilian",
            cost: { wood: 1, clay: 1, ore: 1, stone: 1, glass: 1, loom: 1, papyrus: 1 }, produces: [], producesChoice: false, vp: 8, shields: 0, coinsOnPlay: 0,
            effect: "Worth 8 VP.",
            chainFrom: [], chainTo: [], playerCount: 7 },
        // ---- Yellow (Commercial Structures) ----
        { id: "tavern", name: "Tavern", emoji: "🍺", age: 1, type: "commercial",
            cost: {}, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 5,
            effect: "Gives 5 coins when built.",
            chainFrom: [], chainTo: [], playerCount: 4 },
        { id: "tavern-2", name: "Tavern", emoji: "🍺", age: 1, type: "commercial",
            cost: {}, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 5,
            effect: "Gives 5 coins when built.",
            chainFrom: [], chainTo: [], playerCount: 5 },
        { id: "tavern-3", name: "Tavern", emoji: "🍺", age: 1, type: "commercial",
            cost: {}, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 5,
            effect: "Gives 5 coins when built.",
            chainFrom: [], chainTo: [], playerCount: 7 },
        { id: "west-trading-post", name: "West Trading Post", emoji: "🏪", age: 1, type: "commercial",
            cost: {}, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Buy Wood/Stone/Ore/Clay from your left neighbor for 1 coin instead of 2.",
            chainFrom: [], chainTo: ["forum", "forum-2", "forum-3"], playerCount: 3,
            abilities: [{ kind: "tradeDiscount", category: "basic" }] },
        { id: "west-trading-post-2", name: "West Trading Post", emoji: "🏪", age: 1, type: "commercial",
            cost: {}, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Buy Wood/Stone/Ore/Clay from your left neighbor for 1 coin instead of 2.",
            chainFrom: [], chainTo: ["forum", "forum-2", "forum-3"], playerCount: 7,
            abilities: [{ kind: "tradeDiscount", category: "basic" }] },
        { id: "east-trading-post", name: "East Trading Post", emoji: "🏬", age: 1, type: "commercial",
            cost: {}, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Buy Wood/Stone/Ore/Clay from your right neighbor for 1 coin instead of 2.",
            chainFrom: [], chainTo: ["forum", "forum-2", "forum-3"], playerCount: 3,
            abilities: [{ kind: "tradeDiscount", category: "basic" }] },
        { id: "east-trading-post-2", name: "East Trading Post", emoji: "🏬", age: 1, type: "commercial",
            cost: {}, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Buy Wood/Stone/Ore/Clay from your right neighbor for 1 coin instead of 2.",
            chainFrom: [], chainTo: ["forum", "forum-2", "forum-3"], playerCount: 7,
            abilities: [{ kind: "tradeDiscount", category: "basic" }] },
        { id: "marketplace", name: "Marketplace", emoji: "🛒", age: 1, type: "commercial",
            cost: {}, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Buy Glass/Loom/Papyrus from your neighbors for 1 coin instead of 2.",
            chainFrom: [], chainTo: ["caravansery", "caravansery-2", "caravansery-3"], playerCount: 3,
            abilities: [{ kind: "tradeDiscount", category: "manufactured" }] },
        { id: "marketplace-2", name: "Marketplace", emoji: "🛒", age: 1, type: "commercial",
            cost: {}, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Buy Glass/Loom/Papyrus from your neighbors for 1 coin instead of 2.",
            chainFrom: [], chainTo: ["caravansery", "caravansery-2", "caravansery-3"], playerCount: 6,
            abilities: [{ kind: "tradeDiscount", category: "manufactured" }] },
        { id: "caravansery", name: "Caravansery", emoji: "🐫", age: 2, type: "commercial",
            cost: { wood: 2 }, produces: ["wood", "stone", "ore", "clay"], producesChoice: true, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Produces 1 of your choice: Wood, Stone, Ore, or Clay, every turn.",
            chainFrom: ["marketplace", "marketplace-2"], chainTo: ["lighthouse", "lighthouse-2"], playerCount: 3 },
        { id: "caravansery-2", name: "Caravansery", emoji: "🐫", age: 2, type: "commercial",
            cost: { wood: 2 }, produces: ["wood", "stone", "ore", "clay"], producesChoice: true, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Produces 1 of your choice: Wood, Stone, Ore, or Clay, every turn.",
            chainFrom: ["marketplace", "marketplace-2"], chainTo: ["lighthouse", "lighthouse-2"], playerCount: 5 },
        { id: "caravansery-3", name: "Caravansery", emoji: "🐫", age: 2, type: "commercial",
            cost: { wood: 2 }, produces: ["wood", "stone", "ore", "clay"], producesChoice: true, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Produces 1 of your choice: Wood, Stone, Ore, or Clay, every turn.",
            chainFrom: ["marketplace", "marketplace-2"], chainTo: ["lighthouse", "lighthouse-2"], playerCount: 6 },
        { id: "forum", name: "Forum", emoji: "🏢", age: 2, type: "commercial",
            cost: { clay: 2 }, produces: ["glass", "loom", "papyrus"], producesChoice: true, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Produces 1 of your choice: Glass, Loom, or Papyrus, every turn.",
            chainFrom: ["west-trading-post", "west-trading-post-2", "east-trading-post", "east-trading-post-2"], chainTo: ["haven", "haven-2"], playerCount: 3 },
        { id: "forum-2", name: "Forum", emoji: "🏢", age: 2, type: "commercial",
            cost: { clay: 2 }, produces: ["glass", "loom", "papyrus"], producesChoice: true, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Produces 1 of your choice: Glass, Loom, or Papyrus, every turn.",
            chainFrom: ["west-trading-post", "west-trading-post-2", "east-trading-post", "east-trading-post-2"], chainTo: ["haven", "haven-2"], playerCount: 6 },
        { id: "forum-3", name: "Forum", emoji: "🏢", age: 2, type: "commercial",
            cost: { clay: 2 }, produces: ["glass", "loom", "papyrus"], producesChoice: true, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Produces 1 of your choice: Glass, Loom, or Papyrus, every turn.",
            chainFrom: ["west-trading-post", "west-trading-post-2", "east-trading-post", "east-trading-post-2"], chainTo: ["haven", "haven-2"], playerCount: 7 },
        { id: "vineyard", name: "Vineyard", emoji: "🍇", age: 2, type: "commercial",
            cost: {}, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Gain 1 coin for each Raw Material card in your city and your neighbors' cities.",
            chainFrom: [], chainTo: [], playerCount: 3,
            abilities: [{ kind: "coinsPerCardType", cardType: "basic", per: 1, scope: "selfAndNeighbors" }] },
        { id: "vineyard-2", name: "Vineyard", emoji: "🍇", age: 2, type: "commercial",
            cost: {}, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Gain 1 coin for each Raw Material card in your city and your neighbors' cities.",
            chainFrom: [], chainTo: [], playerCount: 6,
            abilities: [{ kind: "coinsPerCardType", cardType: "basic", per: 1, scope: "selfAndNeighbors" }] },
        { id: "bazaar", name: "Bazaar", emoji: "🏺", age: 2, type: "commercial",
            cost: {}, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Gain 2 coins for each Manufactured Good card in your city and your neighbors' cities.",
            chainFrom: [], chainTo: [], playerCount: 4,
            abilities: [{ kind: "coinsPerCardType", cardType: "manufactured", per: 2, scope: "selfAndNeighbors" }] },
        { id: "bazaar-2", name: "Bazaar", emoji: "🏺", age: 2, type: "commercial",
            cost: {}, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Gain 2 coins for each Manufactured Good card in your city and your neighbors' cities.",
            chainFrom: [], chainTo: [], playerCount: 7,
            abilities: [{ kind: "coinsPerCardType", cardType: "manufactured", per: 2, scope: "selfAndNeighbors" }] },
        { id: "lighthouse", name: "Lighthouse", emoji: "🚨", age: 3, type: "commercial",
            cost: { stone: 1, glass: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Gain 1 coin for each Commercial card in your city (including itself) when built. At game end, worth 1 VP for each Commercial card present in your city.",
            chainFrom: ["caravansery", "caravansery-2", "caravansery-3"], chainTo: [], playerCount: 3,
            abilities: [{ kind: "coinsPerCardType", cardType: "commercial", per: 1, scope: "self", includeSelf: true }, { kind: "vpPerCardType", cardType: "commercial", per: 1, scope: "self", includeSelf: true }] },
        { id: "lighthouse-2", name: "Lighthouse", emoji: "🚨", age: 3, type: "commercial",
            cost: { stone: 1, glass: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Gain 1 coin for each Commercial card in your city (including itself) when built. At game end, worth 1 VP for each Commercial card present in your city.",
            chainFrom: ["caravansery", "caravansery-2", "caravansery-3"], chainTo: [], playerCount: 5,
            abilities: [{ kind: "coinsPerCardType", cardType: "commercial", per: 1, scope: "self", includeSelf: true }, { kind: "vpPerCardType", cardType: "commercial", per: 1, scope: "self", includeSelf: true }] },
        { id: "haven", name: "Haven", emoji: "⚓", age: 3, type: "commercial",
            cost: { wood: 1, ore: 1, loom: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Gain 1 coin for each Raw Material card in your city when built. At game end, worth 1 VP for each Raw Material card present in your city.",
            chainFrom: ["forum", "forum-2", "forum-3"], chainTo: [], playerCount: 3,
            abilities: [{ kind: "coinsPerCardType", cardType: "basic", per: 1, scope: "self" }, { kind: "vpPerCardType", cardType: "basic", per: 1, scope: "self" }] },
        { id: "haven-2", name: "Haven", emoji: "⚓", age: 3, type: "commercial",
            cost: { wood: 1, ore: 1, loom: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Gain 1 coin for each Raw Material card in your city when built. At game end, worth 1 VP for each Raw Material card present in your city.",
            chainFrom: ["forum", "forum-2", "forum-3"], chainTo: [], playerCount: 4,
            abilities: [{ kind: "coinsPerCardType", cardType: "basic", per: 1, scope: "self" }, { kind: "vpPerCardType", cardType: "basic", per: 1, scope: "self" }] },
        { id: "chamber-of-commerce", name: "Chamber of Commerce", emoji: "🏦", age: 3, type: "commercial",
            cost: { clay: 1, papyrus: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Gain 2 coins for each Manufactured Good card in your city when built. At game end, worth 2 VP for each Manufactured Good card present in your city.",
            chainFrom: [], chainTo: [], playerCount: 4,
            abilities: [{ kind: "coinsPerCardType", cardType: "manufactured", per: 2, scope: "self" }, { kind: "vpPerCardType", cardType: "manufactured", per: 2, scope: "self" }] },
        { id: "chamber-of-commerce-2", name: "Chamber of Commerce", emoji: "🏦", age: 3, type: "commercial",
            cost: { clay: 1, papyrus: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Gain 2 coins for each Manufactured Good card in your city when built. At game end, worth 2 VP for each Manufactured Good card present in your city.",
            chainFrom: [], chainTo: [], playerCount: 6,
            abilities: [{ kind: "coinsPerCardType", cardType: "manufactured", per: 2, scope: "self" }, { kind: "vpPerCardType", cardType: "manufactured", per: 2, scope: "self" }] },
        { id: "ludus", name: "Ludus", emoji: "🤼", age: 3, type: "commercial",
            cost: { ore: 1, stone: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Gain 3 coins for each Military card in your city when built. At game end, worth 1 VP for each Military card present in your city.",
            chainFrom: [], chainTo: [], playerCount: 5,
            abilities: [{ kind: "coinsPerCardType", cardType: "military", per: 3, scope: "self" }, { kind: "vpPerCardType", cardType: "military", per: 1, scope: "self" }] },
        { id: "ludus-2", name: "Ludus", emoji: "🤼", age: 3, type: "commercial",
            cost: { ore: 1, stone: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Gain 3 coins for each Military card in your city when built. At game end, worth 1 VP for each Military card present in your city.",
            chainFrom: [], chainTo: [], playerCount: 7,
            abilities: [{ kind: "coinsPerCardType", cardType: "military", per: 3, scope: "self" }, { kind: "vpPerCardType", cardType: "military", per: 1, scope: "self" }] },
        { id: "arena", name: "Arena", emoji: "🏟️", age: 3, type: "commercial",
            cost: { clay: 1, ore: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Gain 3 coins for each Wonder stage you've constructed when built. At game end, worth 1 VP for each Wonder stage you've constructed.",
            chainFrom: ["dispensary", "dispensary-2"], chainTo: [], playerCount: 3,
            abilities: [{ kind: "coinsPerWonderStage", per: 3, scope: "self" }, { kind: "vpPerWonderStage", per: 1, scope: "self" }] },
        { id: "arena-2", name: "Arena", emoji: "🏟️", age: 3, type: "commercial",
            cost: { clay: 1, ore: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Gain 3 coins for each Wonder stage you've constructed when built. At game end, worth 1 VP for each Wonder stage you've constructed.",
            chainFrom: ["dispensary", "dispensary-2"], chainTo: [], playerCount: 5,
            abilities: [{ kind: "coinsPerWonderStage", per: 3, scope: "self" }, { kind: "vpPerWonderStage", per: 1, scope: "self" }] },
        // ---- Red (Military Structures) ----
        { id: "guard-tower", name: "Guard Tower", emoji: "🗼", age: 1, type: "military",
            cost: { clay: 1 }, produces: [], producesChoice: false, vp: 0, shields: 1, coinsOnPlay: 0,
            effect: "Grants 1 Shield.",
            chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "guard-tower-2", name: "Guard Tower", emoji: "🗼", age: 1, type: "military",
            cost: { clay: 1 }, produces: [], producesChoice: false, vp: 0, shields: 1, coinsOnPlay: 0,
            effect: "Grants 1 Shield.",
            chainFrom: [], chainTo: [], playerCount: 4 },
        { id: "barracks", name: "Barracks", emoji: "⚔️", age: 1, type: "military",
            cost: { ore: 1 }, produces: [], producesChoice: false, vp: 0, shields: 1, coinsOnPlay: 0,
            effect: "Grants 1 Shield.",
            chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "barracks-2", name: "Barracks", emoji: "⚔️", age: 1, type: "military",
            cost: { ore: 1 }, produces: [], producesChoice: false, vp: 0, shields: 1, coinsOnPlay: 0,
            effect: "Grants 1 Shield.",
            chainFrom: [], chainTo: [], playerCount: 5 },
        { id: "stockade", name: "Stockade", emoji: "🛡️", age: 1, type: "military",
            cost: { wood: 1 }, produces: [], producesChoice: false, vp: 0, shields: 1, coinsOnPlay: 0,
            effect: "Grants 1 Shield.",
            chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "stockade-2", name: "Stockade", emoji: "🛡️", age: 1, type: "military",
            cost: { wood: 1 }, produces: [], producesChoice: false, vp: 0, shields: 1, coinsOnPlay: 0,
            effect: "Grants 1 Shield.",
            chainFrom: [], chainTo: [], playerCount: 7 },
        { id: "stables", name: "Stables", emoji: "🐎", age: 2, type: "military",
            cost: { wood: 1, clay: 1, ore: 1 }, produces: [], producesChoice: false, vp: 0, shields: 2, coinsOnPlay: 0,
            effect: "Grants 2 Shields.",
            chainFrom: ["apothecary", "apothecary-2"], chainTo: [], playerCount: 3 },
        { id: "stables-2", name: "Stables", emoji: "🐎", age: 2, type: "military",
            cost: { wood: 1, clay: 1, ore: 1 }, produces: [], producesChoice: false, vp: 0, shields: 2, coinsOnPlay: 0,
            effect: "Grants 2 Shields.",
            chainFrom: ["apothecary", "apothecary-2"], chainTo: [], playerCount: 5 },
        { id: "archery-range", name: "Archery Range", emoji: "🏹", age: 2, type: "military",
            cost: { wood: 2, ore: 1 }, produces: [], producesChoice: false, vp: 0, shields: 2, coinsOnPlay: 0,
            effect: "Grants 2 Shields.",
            chainFrom: ["workshop", "workshop-2"], chainTo: [], playerCount: 3 },
        { id: "archery-range-2", name: "Archery Range", emoji: "🏹", age: 2, type: "military",
            cost: { wood: 2, ore: 1 }, produces: [], producesChoice: false, vp: 0, shields: 2, coinsOnPlay: 0,
            effect: "Grants 2 Shields.",
            chainFrom: ["workshop", "workshop-2"], chainTo: [], playerCount: 6 },
        { id: "walls", name: "Walls", emoji: "🧱", age: 2, type: "military",
            cost: { stone: 3 }, produces: [], producesChoice: false, vp: 0, shields: 2, coinsOnPlay: 0,
            effect: "Grants 2 Shields.",
            chainFrom: [], chainTo: ["fortifications", "fortifications-2"], playerCount: 3 },
        { id: "walls-2", name: "Walls", emoji: "🧱", age: 2, type: "military",
            cost: { stone: 3 }, produces: [], producesChoice: false, vp: 0, shields: 2, coinsOnPlay: 0,
            effect: "Grants 2 Shields.",
            chainFrom: [], chainTo: ["fortifications", "fortifications-2"], playerCount: 7 },
        { id: "training-ground", name: "Training Ground", emoji: "🎯", age: 2, type: "military",
            cost: { wood: 1, ore: 2 }, produces: [], producesChoice: false, vp: 0, shields: 2, coinsOnPlay: 0,
            effect: "Grants 2 Shields.",
            chainFrom: [], chainTo: ["circus", "circus-2"], playerCount: 4 },
        { id: "training-ground-2", name: "Training Ground", emoji: "🎯", age: 2, type: "military",
            cost: { wood: 1, ore: 2 }, produces: [], producesChoice: false, vp: 0, shields: 2, coinsOnPlay: 0,
            effect: "Grants 2 Shields.",
            chainFrom: [], chainTo: ["circus", "circus-2"], playerCount: 6 },
        { id: "training-ground-3", name: "Training Ground", emoji: "🎯", age: 2, type: "military",
            cost: { wood: 1, ore: 2 }, produces: [], producesChoice: false, vp: 0, shields: 2, coinsOnPlay: 0,
            effect: "Grants 2 Shields.",
            chainFrom: [], chainTo: ["circus", "circus-2"], playerCount: 7 },
        { id: "arsenal", name: "Arsenal", emoji: "🏹", age: 3, type: "military",
            cost: { wood: 2, clay: 1, ore: 1 }, produces: [], producesChoice: false, vp: 0, shields: 3, coinsOnPlay: 0,
            effect: "Grants 3 Shields.",
            chainFrom: [], chainTo: [], playerCount: 3 },
        { id: "arsenal-2", name: "Arsenal", emoji: "🏹", age: 3, type: "military",
            cost: { wood: 2, clay: 1, ore: 1 }, produces: [], producesChoice: false, vp: 0, shields: 3, coinsOnPlay: 0,
            effect: "Grants 3 Shields.",
            chainFrom: [], chainTo: [], playerCount: 5 },
        { id: "siege-workshop", name: "Siege Workshop", emoji: "🏕️", age: 3, type: "military",
            cost: { wood: 1, clay: 3 }, produces: [], producesChoice: false, vp: 0, shields: 3, coinsOnPlay: 0,
            effect: "Grants 3 Shields.",
            chainFrom: ["laboratory", "laboratory-2"], chainTo: [], playerCount: 3 },
        { id: "siege-workshop-2", name: "Siege Workshop", emoji: "🏕️", age: 3, type: "military",
            cost: { wood: 1, clay: 3 }, produces: [], producesChoice: false, vp: 0, shields: 3, coinsOnPlay: 0,
            effect: "Grants 3 Shields.",
            chainFrom: ["laboratory", "laboratory-2"], chainTo: [], playerCount: 5 },
        { id: "fortifications", name: "Fortifications", emoji: "🏯", age: 3, type: "military",
            cost: { clay: 1, ore: 3 }, produces: [], producesChoice: false, vp: 0, shields: 3, coinsOnPlay: 0,
            effect: "Grants 3 Shields.",
            chainFrom: ["walls", "walls-2"], chainTo: [], playerCount: 3 },
        { id: "fortifications-2", name: "Fortifications", emoji: "🏯", age: 3, type: "military",
            cost: { clay: 1, ore: 3 }, produces: [], producesChoice: false, vp: 0, shields: 3, coinsOnPlay: 0,
            effect: "Grants 3 Shields.",
            chainFrom: ["walls", "walls-2"], chainTo: [], playerCount: 7 },
        { id: "circus", name: "Circus", emoji: "🎪", age: 3, type: "military",
            cost: { wood: 1, clay: 2, ore: 1 }, produces: [], producesChoice: false, vp: 0, shields: 3, coinsOnPlay: 0,
            effect: "Grants 3 Shields.",
            chainFrom: ["training-ground", "training-ground-2", "training-ground-3"], chainTo: [], playerCount: 4 },
        { id: "circus-2", name: "Circus", emoji: "🎪", age: 3, type: "military",
            cost: { wood: 1, clay: 2, ore: 1 }, produces: [], producesChoice: false, vp: 0, shields: 3, coinsOnPlay: 0,
            effect: "Grants 3 Shields.",
            chainFrom: ["training-ground", "training-ground-2", "training-ground-3"], chainTo: [], playerCount: 6 },
        { id: "castrum", name: "Castrum", emoji: "🏰", age: 3, type: "military",
            cost: { wood: 1, clay: 2, papyrus: 1 }, produces: [], producesChoice: false, vp: 0, shields: 3, coinsOnPlay: 0,
            effect: "Grants 3 Shields.",
            chainFrom: [], chainTo: [], playerCount: 4 },
        { id: "castrum-2", name: "Castrum", emoji: "🏰", age: 3, type: "military",
            cost: { wood: 1, clay: 2, papyrus: 1 }, produces: [], producesChoice: false, vp: 0, shields: 3, coinsOnPlay: 0,
            effect: "Grants 3 Shields.",
            chainFrom: [], chainTo: [], playerCount: 7 },
        // ---- Green (Scientific Structures) ----
        { id: "scriptorium", name: "Scriptorium", emoji: "📚", age: 1, type: "scientific",
            cost: { papyrus: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Grants a Tablet science symbol.",
            chainFrom: [], chainTo: ["courthouse", "courthouse-2", "library", "library-2"], playerCount: 3,
            abilities: [{ kind: "science", symbol: "tablet" }] },
        { id: "scriptorium-2", name: "Scriptorium", emoji: "📚", age: 1, type: "scientific",
            cost: { papyrus: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Grants a Tablet science symbol.",
            chainFrom: [], chainTo: ["courthouse", "courthouse-2", "library", "library-2"], playerCount: 4,
            abilities: [{ kind: "science", symbol: "tablet" }] },
        { id: "apothecary", name: "Apothecary", emoji: "🧪", age: 1, type: "scientific",
            cost: { loom: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Grants a Compass science symbol.",
            chainFrom: [], chainTo: ["stables", "stables-2", "dispensary", "dispensary-2"], playerCount: 3,
            abilities: [{ kind: "science", symbol: "compass" }] },
        { id: "apothecary-2", name: "Apothecary", emoji: "🧪", age: 1, type: "scientific",
            cost: { loom: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Grants a Compass science symbol.",
            chainFrom: [], chainTo: ["stables", "stables-2", "dispensary", "dispensary-2"], playerCount: 5,
            abilities: [{ kind: "science", symbol: "compass" }] },
        { id: "workshop", name: "Workshop", emoji: "⚙️", age: 1, type: "scientific",
            cost: { glass: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Grants a Gear science symbol.",
            chainFrom: [], chainTo: ["archery-range", "archery-range-2", "laboratory", "laboratory-2"], playerCount: 3,
            abilities: [{ kind: "science", symbol: "gear" }] },
        { id: "workshop-2", name: "Workshop", emoji: "⚙️", age: 1, type: "scientific",
            cost: { glass: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Grants a Gear science symbol.",
            chainFrom: [], chainTo: ["archery-range", "archery-range-2", "laboratory", "laboratory-2"], playerCount: 7,
            abilities: [{ kind: "science", symbol: "gear" }] },
        { id: "dispensary", name: "Dispensary", emoji: "🧭", age: 2, type: "scientific",
            cost: { ore: 2, glass: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Grants a Compass science symbol.",
            chainFrom: ["apothecary", "apothecary-2"], chainTo: ["arena", "arena-2", "lodge", "lodge-2"], playerCount: 3,
            abilities: [{ kind: "science", symbol: "compass" }] },
        { id: "dispensary-2", name: "Dispensary", emoji: "🧭", age: 2, type: "scientific",
            cost: { ore: 2, glass: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Grants a Compass science symbol.",
            chainFrom: ["apothecary", "apothecary-2"], chainTo: ["arena", "arena-2", "lodge", "lodge-2"], playerCount: 4,
            abilities: [{ kind: "science", symbol: "compass" }] },
        { id: "laboratory", name: "Laboratory", emoji: "🔬", age: 2, type: "scientific",
            cost: { clay: 2, papyrus: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Grants a Gear science symbol.",
            chainFrom: ["workshop", "workshop-2"], chainTo: ["siege-workshop", "siege-workshop-2", "observatory", "observatory-2"], playerCount: 3,
            abilities: [{ kind: "science", symbol: "gear" }] },
        { id: "laboratory-2", name: "Laboratory", emoji: "🔬", age: 2, type: "scientific",
            cost: { clay: 2, papyrus: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Grants a Gear science symbol.",
            chainFrom: ["workshop", "workshop-2"], chainTo: ["siege-workshop", "siege-workshop-2", "observatory", "observatory-2"], playerCount: 5,
            abilities: [{ kind: "science", symbol: "gear" }] },
        { id: "library", name: "Library", emoji: "📖", age: 2, type: "scientific",
            cost: { stone: 2, loom: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Grants a Tablet science symbol.",
            chainFrom: ["scriptorium", "scriptorium-2"], chainTo: ["senate", "senate-2", "university", "university-2"], playerCount: 3,
            abilities: [{ kind: "science", symbol: "tablet" }] },
        { id: "library-2", name: "Library", emoji: "📖", age: 2, type: "scientific",
            cost: { stone: 2, loom: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Grants a Tablet science symbol.",
            chainFrom: ["scriptorium", "scriptorium-2"], chainTo: ["senate", "senate-2", "university", "university-2"], playerCount: 6,
            abilities: [{ kind: "science", symbol: "tablet" }] },
        { id: "school", name: "School", emoji: "🏫", age: 2, type: "scientific",
            cost: { wood: 1, papyrus: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Grants a Tablet science symbol.",
            chainFrom: [], chainTo: ["academy", "academy-2", "study", "study-2"], playerCount: 3,
            abilities: [{ kind: "science", symbol: "tablet" }] },
        { id: "school-2", name: "School", emoji: "🏫", age: 2, type: "scientific",
            cost: { wood: 1, papyrus: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Grants a Tablet science symbol.",
            chainFrom: [], chainTo: ["academy", "academy-2", "study", "study-2"], playerCount: 7,
            abilities: [{ kind: "science", symbol: "tablet" }] },
        { id: "university", name: "University", emoji: "🎓", age: 3, type: "scientific",
            cost: { wood: 2, glass: 1, papyrus: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Grants a Tablet science symbol.",
            chainFrom: ["library", "library-2"], chainTo: [], playerCount: 3,
            abilities: [{ kind: "science", symbol: "tablet" }] },
        { id: "university-2", name: "University", emoji: "🎓", age: 3, type: "scientific",
            cost: { wood: 2, glass: 1, papyrus: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Grants a Tablet science symbol.",
            chainFrom: ["library", "library-2"], chainTo: [], playerCount: 4,
            abilities: [{ kind: "science", symbol: "tablet" }] },
        { id: "study", name: "Study", emoji: "📖", age: 3, type: "scientific",
            cost: { wood: 1, loom: 1, papyrus: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Grants a Gear science symbol.",
            chainFrom: ["school", "school-2"], chainTo: [], playerCount: 3,
            abilities: [{ kind: "science", symbol: "gear" }] },
        { id: "study-2", name: "Study", emoji: "📖", age: 3, type: "scientific",
            cost: { wood: 1, loom: 1, papyrus: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Grants a Gear science symbol.",
            chainFrom: ["school", "school-2"], chainTo: [], playerCount: 5,
            abilities: [{ kind: "science", symbol: "gear" }] },
        { id: "lodge", name: "Lodge", emoji: "🧭", age: 3, type: "scientific",
            cost: { clay: 2, loom: 1, papyrus: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Grants a Compass science symbol.",
            chainFrom: ["dispensary", "dispensary-2"], chainTo: [], playerCount: 3,
            abilities: [{ kind: "science", symbol: "compass" }] },
        { id: "lodge-2", name: "Lodge", emoji: "🧭", age: 3, type: "scientific",
            cost: { clay: 2, loom: 1, papyrus: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Grants a Compass science symbol.",
            chainFrom: ["dispensary", "dispensary-2"], chainTo: [], playerCount: 6,
            abilities: [{ kind: "science", symbol: "compass" }] },
        { id: "academy", name: "Academy", emoji: "🏛️", age: 3, type: "scientific",
            cost: { stone: 2, glass: 1, papyrus: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Grants a Compass science symbol.",
            chainFrom: ["school", "school-2"], chainTo: [], playerCount: 3,
            abilities: [{ kind: "science", symbol: "compass" }] },
        { id: "academy-2", name: "Academy", emoji: "🏛️", age: 3, type: "scientific",
            cost: { stone: 2, glass: 1, papyrus: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Grants a Compass science symbol.",
            chainFrom: ["school", "school-2"], chainTo: [], playerCount: 7,
            abilities: [{ kind: "science", symbol: "compass" }] },
        { id: "observatory", name: "Observatory", emoji: "🔭", age: 3, type: "scientific",
            cost: { ore: 2, glass: 1, loom: 1, papyrus: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Grants a Gear science symbol.",
            chainFrom: ["laboratory", "laboratory-2"], chainTo: [], playerCount: 3,
            abilities: [{ kind: "science", symbol: "gear" }] },
        { id: "observatory-2", name: "Observatory", emoji: "🔭", age: 3, type: "scientific",
            cost: { ore: 2, glass: 1, loom: 1, papyrus: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "Grants a Gear science symbol.",
            chainFrom: ["laboratory", "laboratory-2"], chainTo: [], playerCount: 7,
            abilities: [{ kind: "science", symbol: "gear" }] },
        // ---- Purple (Guilds) — no player-count scaling; Guild count kept at a game is `numPlayers + 2` (docs/rules.md), handled by buildDeckPools, not per-card playerCount ----
        { id: "workers-guild", name: "Workers Guild", emoji: "👷", age: 3, type: "guild",
            cost: { wood: 1, clay: 1, ore: 2, papyrus: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "At game end, gain 1 VP for each Raw Material card present in both neighboring cities.",
            chainFrom: [], chainTo: [], playerCount: 3,
            abilities: [{ kind: "countCardType", cardType: "basic", scope: "neighbors", per: 1 }] },
        { id: "craftsmens-guild", name: "Craftsmens Guild", emoji: "🛠️", age: 3, type: "guild",
            cost: { ore: 1, stone: 2 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "At game end, gain 2 VP for each Manufactured Good card present in both neighboring cities.",
            chainFrom: [], chainTo: [], playerCount: 3,
            abilities: [{ kind: "countCardType", cardType: "manufactured", scope: "neighbors", per: 2 }] },
        { id: "magistrates-guild", name: "Magistrates Guild", emoji: "⚖️", age: 3, type: "guild",
            cost: { wood: 3, ore: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "At game end, gain 1 VP for each Civilian card present in both neighboring cities.",
            chainFrom: [], chainTo: [], playerCount: 3,
            abilities: [{ kind: "countCardType", cardType: "civilian", scope: "neighbors", per: 1 }] },
        { id: "traders-guild", name: "Traders Guild", emoji: "🧳", age: 3, type: "guild",
            cost: { glass: 1, loom: 1, papyrus: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "At game end, gain 1 VP for each Commercial card present in both neighboring cities.",
            chainFrom: [], chainTo: [], playerCount: 3,
            abilities: [{ kind: "countCardType", cardType: "commercial", scope: "neighbors", per: 1 }] },
        { id: "spies-guild", name: "Spies Guild", emoji: "🕵️", age: 3, type: "guild",
            cost: { clay: 2, glass: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "At game end, gain 1 VP for each Military card present in both neighboring cities.",
            chainFrom: [], chainTo: [], playerCount: 3,
            abilities: [{ kind: "countCardType", cardType: "military", scope: "neighbors", per: 1 }] },
        { id: "philosophers-guild", name: "Philosophers Guild", emoji: "📖", age: 3, type: "guild",
            cost: { clay: 3, loom: 1, papyrus: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "At game end, gain 1 VP for each Scientific card present in both neighboring cities.",
            chainFrom: [], chainTo: [], playerCount: 3,
            abilities: [{ kind: "countCardType", cardType: "scientific", scope: "neighbors", per: 1 }] },
        { id: "shipowners-guild", name: "Shipowners Guild", emoji: "🚢", age: 3, type: "guild",
            cost: { wood: 3, glass: 1, papyrus: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "At game end, gain 1 VP for each Raw Material, Manufactured Good, and Guild card in your city.",
            chainFrom: [], chainTo: [], playerCount: 3,
            abilities: [{ kind: "countCardTypes", cardTypes: ["basic", "manufactured", "guild"], scope: "self", per: 1 }] },
        { id: "scientists-guild", name: "Scientists Guild", emoji: "🔬", age: 3, type: "guild",
            cost: { wood: 2, ore: 2, papyrus: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "At game end, gain an extra scientific symbol of your choice.",
            chainFrom: [], chainTo: [], playerCount: 3,
            abilities: [{ kind: "extraScienceSymbol" }] },
        { id: "decorators-guild", name: "Decorators Guild", emoji: "🎀", age: 3, type: "guild",
            cost: { ore: 2, stone: 1, loom: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "At game end, gain 7 VP only if all stages of your Wonder are constructed.",
            chainFrom: [], chainTo: [], playerCount: 3,
            abilities: [{ kind: "wonderCompleteBonus", vp: 7 }] },
        { id: "builders-guild", name: "Builders Guild", emoji: "🏗️", age: 3, type: "guild",
            cost: { clay: 1, stone: 3, glass: 1 }, produces: [], producesChoice: false, vp: 0, shields: 0, coinsOnPlay: 0,
            effect: "At game end, gain 1 VP for each Wonder stage constructed in your city and your neighbors' cities.",
            chainFrom: [], chainTo: [], playerCount: 3,
            abilities: [{ kind: "countWonderStages", scope: "neighborsAndSelf", per: 1 }] },
    ],
};
if (typeof module !== "undefined" && module.exports)
    module.exports = GameData;
